### ISSUE TITLE
使用<table>标签转后页面出现一排的<br>

### ISSUE THREAD

**Issue by viperasi** [tankywoo/simiki#100]
在md文件中使用<table>标签创建表格，生成后的文件在表格前生成了很多的`<br>`。不知道是设置问题还是平台问题，望解答，谢谢。

版本:
simiki 1.6.2.1
python 2.7.13

平台:
Windows 10

**Comment by viperasi** [comment]
在table上一行加一个回车就可以了，看来还是编写的问题吗？

**Comment by tankywoo** [comment]
能否贴个例子？

**Comment by viperasi** [comment]
`## title`  
`<table>`  
`<tr>`  
`<td>123123</td>`  
`</tr>`  
`</table>`  
生成后的结果是
`<h2 id="title">title</h2>`  
`<p><table><br />`  
`<tr><br />`  
`<td>123123</td><br />`  
`</tr><br />`  
`</table></p>`  

但是在`<table>`标记前手动换一个下行，就没这个问题。
前面生成的空格数是我代码里换行的数。

**Comment by tankywoo** [comment]
感谢。测试确实如此，因为近期默认开启了 `nl2br` 功能，也就是符合 GFM 的换行行为，但是makrdown引擎在这块处理看来有点问题，我给官方报个Issue。

**Comment by tankywoo** [comment]
See https://github.com/waylan/Python-Markdown/issues/574

**Comment by tankywoo** [comment]
@viperasi 官方已经回答，这个是 Markdown 标准的行为，所以没有问题。GFM 是额外定义了一些准则。具体可以看看上面这个 Issue。

**Comment by viperasi** [comment]
@tankywoo 收到，谢谢，原来是标准就要这样吗。
