### ISSUE TITLE
两层目录的路径少了一层，导致404

### ISSUE THREAD

**Issue by thqy39** [tankywoo/simiki#101]
2017-07 : 
Week01 /  Week02 /  Week03 /  Week04
2017-08 : 
Week01 /  Week02 /  Week03 /  Week03

这些Week都找不到

<div class="list_wrapper">
                <div class="coll_name item_arrow">2017-08&nbsp;&#58;&nbsp;</div>
                <div class="coll_list">
                  <a href="./work-report/08Week01.html">Week01</a>&nbsp;&#47;&nbsp;
                  <a href="./work-report/08Week02.html">Week02</a>&nbsp;&#47;&nbsp;
                  <a href="./work-report/08Week03.html">Week03</a>&nbsp;&#47;&nbsp;
                  <a href="./work-report/08Week04.html">Week04</a>
                </div>
              </div>

**Comment by thqy39** [comment]
感谢作者的开源，东西很喜欢，希望这个简单的功能可以被修复

**Comment by thqy39** [comment]
http://thqy39.coding.me/WIKI/
错误就是里面那个123：3test 无法访问 我看了一下html 少拼了 123这个文件夹的名字，或者output的时候把3test拿出来，而不是放在123中

**Comment by thqy39** [comment]
通过 集合  解决了，没事了 我关掉啦

**Comment by tankywoo** [comment]
抱歉前两天有事没看Github。

因为考虑个人使用和主题开发的复杂性，所以默认主题不支持多级目录结构，集合是更深一级的替代品， 👍 

谢谢支持。

**Comment by gitGksgk** [comment]
简单，主题里的index.html里，找到
           `   {%- for coll_page in coll.pages %}
	      <a href="./{{ category.name }}/{{ coll_page.name }}.html">{{ coll_page.title }}</a>
                {%- if 'description' in coll_page %}
                  &nbsp;{{ coll_page.description }}
                {% endif %}
                {%- if not loop.last %}&nbsp;&#47;&nbsp;{% endif %}
              {%- endfor %}`
改为
       `       {%- for coll_page in coll.pages %}
	      <a href="./{{ category.name }}/{{coll.name}}/{{ coll_page.name }}.html">{{ coll_page.title }}</a>
                {%- if 'description' in coll_page %}
                  &nbsp;{{ coll_page.description }}
                {% endif %}
                {%- if not loop.last %}&nbsp;&#47;&nbsp;{% endif %}
              {%- endfor %}`
即可
