### ISSUE TITLE
单个md文件在首页显示的顺序

### ISSUE THREAD

**Issue by ghostlyman** [tankywoo/simiki#111]
经测试（xuxuehua.com Test选项），排序是按照数字字母从小到大排序的。
如果我做的wiki希望大的数字或字母排在前几位，是不是只能通过1_   a_这种方式实现呢？

而且发现通过`simiki  n -t A -c test` 和 `simiki  n -t a -c test` 生成的文件是一样的，会覆盖，这是默认设置吗？

**Comment by tankywoo** [comment]
1. 排序是转为小写按ascii排序，可以通过你说的方式来排序。

2. 生成的文件会根据 title 转为小写本地存储，所以你两条命令生成的文件名一样，不会覆盖，会提示文件已存在。

**Comment by ghostlyman** [comment]
明白了，谢谢
