### ISSUE TITLE
Simiki.org site is currently inaccessible

### ISSUE THREAD

**Issue by longshilin** [tankywoo/simiki#117]
The Simiki.org site is currently inaccessible

![image](https://user-images.githubusercontent.com/18352884/45254512-1271e100-b3ac-11e8-8ac0-79675d714a32.png)  You have reached a domain that is pending ICANN verification.

**Comment by tankywoo** [comment]
Thanks for your report. That's a strange problem which happened some days ago, I guess it's caused by domain whoisguard protection, and I will fix it ASAP.

**Comment by tankywoo** [comment]
The site is ok now.
