### ISSUE TITLE
Break change for the default theme

### ISSUE THREAD

**Issue by lord63** [tankywoo/simiki#118]
## Problem

When I update simiki from 1.5.1 to 1.6.2.1, I found that `simiki p -w` couldn't work any more.  That's because my default theme is simple, but in 1.6.2.1, the default theme is simple2, simiki can't find the simple2 theme to generate pages.

My quick fix is that add `theme: simple` in the configuration file.

## How to reproduce the problem?

I guess use old simiki without specified the theme, and update to latest simiki should meet this problem.

---

I've send a [PR](https://github.com/tankywoo/simiki.org/pull/3) to update the docs.  Maybe an upgrade guide should be added or just a reminder that users should be caution about this change.

**Comment by tankywoo** [comment]
Thanks for your reminder. 👍
