### ISSUE TITLE
win10安装报错：python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by Kmyu1k** [tankywoo/simiki#124]
![image](https://user-images.githubusercontent.com/18068026/56903807-9e698200-6acf-11e9-9c95-7813dbb3012d.png)

windows10 安装报错

**Comment by tankywoo** [comment]
python 版本是多少？

**Comment by Kmyu1k** [comment]
> python 版本是多少？

python 3.6.3

**Comment by tankywoo** [comment]
在 v1.6.2.3 修复了。

ref: https://github.com/google/tangent/issues/11
