### ISSUE TITLE
raise Exception('extracting page with format error,  执行simiki g报错。

### ISSUE THREAD

**Issue by Kmyu1k** [tankywoo/simiki#125]
![image](https://user-images.githubusercontent.com/18068026/57580174-c813a780-74d8-11e9-88c6-c8e317ad877b.png)

我直接复制_config.yml的配置，再执行simiki g也不行

**Comment by tankywoo** [comment]
应该是哪篇 wiki 的 front matter 有问题。

是新建的 wiki 有问题还是？

**Comment by Kmyu1k** [comment]
> 应该是哪篇 wiki 的 front matter 有问题。
> 
> 是新建的 wiki 有问题还是？

不是新建的，是从其他文档复制下来的，新建的markdown文件要设置相应的标题格式才能正确执行吗？

**Comment by tankywoo** [comment]
是的，新建 wiki 会随带一篇 demo wiki，可以参考。

另外你的错误图片最后一行也写了参考链接。

**Comment by Kmyu1k** [comment]
好的 谢谢。
