### ISSUE TITLE
cli中或者配置中应添加系统默认主题切换的配置

### ISSUE THREAD

**Issue by duoduo369** [tankywoo/simiki#22]
simiki默认使用simple主题，如果开发者为simple定制了几套不同的主题，并且放入simiki**源码**的themes文件中，貌似现在simiki没有什么机制能够自动在gen的时候将这个主题copy过来，需要手工cp到生成的wiki themes文件夹中。
cli或者配置中应该添加某个命令实现这件事情。

**Comment by tankywoo** [comment]
Add `--update-theme` option to update theme when generate, link to 0a9511e
