### ISSUE TITLE
能否提供一个小白的部署方法或其它类似参考文章？

### ISSUE THREAD

**Issue by huangkewang** [tankywoo/simiki#23]
如题，我想部署在自己的服务器上。

**Comment by siton** [comment]
加一个：
root: /wiki后，远程pages服务theme效果正常，但本地simiki preview时又会丢失theme渲染效果。

**Comment by lord63** [comment]
@siton, have you ever try `simiki generate --ignore-root`?
>
NOTE:

>If root is setted in _config.yml, you should use --ignore-root when you want to preview in local environment. And regenerate without --ignore-root when you prepare to deploy to remote server.

>    simiki generate --ignore-root

Documentation: <http://simiki.org/docs/deploy.html>

**Comment by tankywoo** [comment]
@lord63 :+1:

**Comment by tankywoo** [comment]
@lord63 @siton 这块其实应该有更好的方式去解决, 但是暂时还没找到方法。这个问题我一直记录着在。

`--ignore-root` 算是一个现阶段的临时解决办法，但是不够优美智能。

**Comment by MForever78** [comment]
@tankywoo Nice work!

可不可增加一个布署的命令，类似于 hexo deploy。在 _config.yaml 里指定 deploy 的方法，github, git, rsync 之类。

**Comment by tankywoo** [comment]
@MForever78 :+1: add to todo, 这个功能很重要，后续会加入

**Comment by zyearn** [comment]
@tankywoo 
1. preview的时候，如果有一个文档修改了，现在是不是需要手动control C然后重新起命令？Octopress是直接监控到变化的文件然后自动显示这个变化的。是不是应该加个这个功能？
2. 文档的title里是不是还不支持书名号？我写在title里，比如title: "<<linux内核开发>>笔记"，generate然后preview，显示的是空title。

**Comment by tankywoo** [comment]
@zyearn 
1. 恩，这个功能还没有去实现，后续会加上
2. 如果你的title是"<abc>笔记"，generate后preview应该显示的是"笔记"吧。这个是html转义的问题。实际的html是:

    <div><abc>笔记</div>

html会认为是abc是一个html标签。

这个涉及到Jinja2模板的转义配置，我暂时还没考虑好是否要做这个处理。

如果你需要在title上使用到`<`, `>`这类符号，可以修改模板，grep `page.title` 和 `page_v.title`，并改为`page.title|e` 和 `page_v.title|e`，使其在generate时转义。

**Comment by zyearn** [comment]
@tankywoo 好的，多谢！

**Comment by tankywoo** [comment]
@lord63 @siton 

See 8c472dfd , removed `--ignore-root`, setting `root` when preview is no difference on local or remote.

**Comment by zvving** [comment]
附上一篇自动部署到 github pages 的介绍 http://www.jianshu.com/p/d56008e6c2e1

**Comment by tankywoo** [comment]
@zvving Cool! 我看了两边，还没试过。

* `which`那个问题已经有朋友提交pr了，下一个relase修复
* 这个被加密的私钥(.enc)的环境变量等是在travis提供的？
* 你得「问题2」，我看是github user page，生成输出应该在master分支，源文件在source分支，你现在以wiki分支作为source，_config.yml中`branch`设置master没问题，且master作为了「默认分支」，则你clone下来，checkout的branch还是master，即用master下的文件执行`simiki g`，并不是wiki分支。

**Comment by zvving** [comment]
@tankywoo 

- .enc 的环境变量在 travis 的网页端管理界面输入。
- 关于『问题二』：
    - .travis.yml 文件中已经配置了 only branch wiki，所以默认 travis-ci 拉的分支已经是 wiki 分支
    - 分支命名是不规范，master 下还有源文件，有后续会整理下
    - https://github.com/davisp/ghp-import/pull/32 已经 merge 了，我之后加 --force 参数再试试。如果 push 还有问题再发 issues

还有希望在生成的 Wiki 页面（如果判断是部署到 Github Page）增加编辑按钮。如：https://github.com/zvving/zvving.github.io/edit/source/content/mac/ruby-env.md 这样全部通过 web 浏览编辑又方便一层。

**Comment by Xuanwo** [comment]
@zvving 这个可以用 travis 的命令行工具来生成

```
gem install travis
travis encrypt-file ssh_key --add
```

可以参考 https://xuanwo.org/2015/02/07/Travis-CI-Hexo-Autodeploy/ 以及 我用于simiki的`[travis.yml](https://github.com/Xuanwo/CLIWiki/blob/master/.travis.yml)`

不过在授权travis的时候，只需要勾选push，就可以规避这个问题。

**Comment by tankywoo** [comment]
@zvving 

> 还有希望在生成的 Wiki 页面（如果判断是部署到 Github Page）增加编辑按钮。如：https://github.com/zvving/zvving.github.io/edit/source/content/mac/ruby-env.md 这样全部通过 web 浏览编辑又方便一层。

你是指页面上增加一个编辑托管在github上源文件的链接？

**Comment by tankywoo** [comment]
@zvving 你的 `--force` 的问题我解决了，这个原因比较坑，本质是：

> Travis CI 做clone时加了`--depth`操作，这个是克隆单分支的；所以你push时，生成的gh-pages分支和之前的gh-pages分支没有连接起来。

最简单的是加上`--no-single-branch`选项，但是travis ci不支持做除了depth层级外的其它选项。

所以我只能加了一些hack操作，手动把分支fetch下来:

    # hack for git clone with `--depth` only single branch
    - git fetch origin gh-pages:refs/remotes/origin/gh-pages
    - git branch gh-pages origin/gh-pages

可以看看我的这个生成log

---

另外， @zvving @Xuanwo 我这边发现clone的是https的地址，需要输入username/password，不是走的ssh/git协议，所以我额外hack:

    - git remote set-url origin git@github.com:tankywoo/wiki.tankywoo.com.git

我看你们没有遇到，你们那边是怎么解决的？

**Comment by Xuanwo** [comment]
我用于部署的gh-pages分支是自己手动clone的，所以没有遇到这个问题

Tanky Woo <notifications@github.com>于2016年2月17日周三 下午4:49写道：

**Comment by zvving** [comment]
@tankywoo 

- wiki 编辑链接：是这个意思，这样浏览、编辑全部通过网页来进行。不过也可能是我一个人的小众需求哈
- `--forece` 多谢！应该是这个问题
- git remote url 我也是这样做的

**Comment by Xuanwo** [comment]
@zvving 能做到这个的话，就不是静态网页啦，不过可以提供本地的前端UI，就看有没有接手这项工作了，233

**Comment by tankywoo** [comment]
@zvving 这个功能目前不会考虑；你也可以在页面增加一个链接，直接指向github上源文件的edit链接也可以。

格式:

    https://github.com/<username>/<project name>/edit/master/path/to/file

另外，这个帖子我先Close了，后续有其它问题可以另开相关的Issue

**Comment by K7777777** [comment]
@tankywoo  你好，我是一个行业新人，使用您的作品。老是无法发表文章。您的帮助文档实在太简单了，我也google了好多，而且。想法联系过很多使用者，希望解决。

[root@centos-linux ~]# simiki new | n -c "Simiki" -t "linux" -f "xx"
-bash: n: command not found
Traceback (most recent call last):
  File "/usr/bin/simiki", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.6/site-packages/simiki/cli.py", line 403, in main
    create_new_wiki(args["-c"], args["-t"], args["-f"])
  File "/usr/lib/python2.6/site-packages/simiki/cli.py", line 92, in create_new_wiki
    _title = title.replace(os.sep, " slash ").lower()
AttributeError: 'NoneType' object has no attribute 'replace'
[root@centos-linux ~]# 

希望您解答一下，或者给一份详细的使用帮助文档。
在此表示感谢。

**Comment by tankywoo** [comment]
@K7777777 你好

```
simiki new | n -t <title> -c <category> [-f <file>]
```

其中 `new | n` 格式表示使用新建文件的子命令 `new` 或者 `n` 都可以，增加`n` 是为了作为 `new` 的简写。

所以你应该直接写为：

```
simiki n -c "Simiki" -t "linux" -f "xx"
```

快速上手使用可以参考：http://simiki.org/quickstart.html

也感谢你的建议，我会考虑将帮助文档再写详细些。

如果还有其它问题，欢迎新开一个 Issue 👍
