### ISSUE TITLE
是否支持windows平台部署wiki?

### ISSUE THREAD

**Issue by jptiancai** [tankywoo/simiki#33]
**安装步骤如下**

- 安装`pip`
- 执行安装命令`pip install simiki`时出错.

**错误日志**

```
    building 'Crypto.Random.OSRNG.winrandom' extension

    warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastm
ath.

    error: Unable to find vcvarsall.bat

    ----------------------------------------
    Command "C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:
\\users\\zhajiang\\appdata\\local\\temp\\pip-build-lkn2u8\\pycrypto\\setup.py';e
xec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n
'), __file__, 'exec'))" install --record c:\users\zhajiang\appdata\local\temp\pi
p-cuyemz-record\install-record.txt --single-version-externally-managed --compile
" failed with error code 1 in c:\users\zhajiang\appdata\local\temp\pip-build-lkn
2u8\pycrypto
```

**Comment by tankywoo** [comment]
支持性不太好，因为很少在win下测试过。

这个是`Fabric`模块的依赖，在win下需要单独安装([reference](http://stackoverflow.com/questions/11405549/how-do-i-install-pycrypto-on-windows)):

    easy_install http://www.voidspace.org.uk/downloads/pycrypto26/pycrypto-2.6.win32-py2.7.exe

安装后再次安装Simiki.

如果再提示缺少`ecsda`，则`pip install`或`easy_install`安装即可。

稍后我会把这块整理到文档，感谢你的提醒。

**Comment by jptiancai** [comment]
不客气,看到回复马上试了试,这一次安装没有错误提示.
下面是成功安装后的页面
```
Successfully installed Fabric Jinja2 Markdown PyYAML Pygments docopt ecdsa marku
psafe ordereddict paramiko-1.15.2 simiki
```

另外,如果修改后,需要再次运行`simiki generate`-->`simiki preview`,相当于一个重新编译的过程,希望在`Getting Started`中注明一下

**Comment by jptiancai** [comment]
另外,运行命令`simiki generate`后,控制台显示
```
[[1;32mINFO[0m]: Serving at port 8000
```

其中`[[1;32mINFO[0m]`根本看不懂,我在`windows 7 控制台`上运行,是不是会有颜色的不一样.

**Comment by tankywoo** [comment]
@jptiancai 

> 另外,如果修改后任何一个.md文件,需要再次运行simiki generate-->simiki preview,直接运行simiki preview是无效的的,相当于一个重新编译的过程,希望在Getting Started中注明一下

这个其实看子命令就能明白含义，generate是生成，preview是预览；修改完后是需要更新页面的，这是框架的特点。

当然这块，考虑会在preview时加一个参数，用于预览时先生成一份

关于`simiki -h`的帮助信息，我也会考虑再补充详细些，谢谢。

> 其中[[1;32mINFO[0m]根本看不懂,我在windows 7 控制台上运行,是不是会有颜色的不一样.

是的，这个在Unix/Linux/Mac下是正常工作的，Win下暂时还没去考虑。只是单纯的做一个颜色的高亮。

如果可能，还是建议在Unix/Linux/Mac下使用比较方便。

**Comment by lord63** [comment]
@jptiancai 

* 关于本地预览，最开始我是开两个标签，一个开 server， 一个时不时 generate，
后来我自己用 [pyinotify][] 写了个快糙猛的 watch.py， 监视 content 目录，有变化时 generate
一下。也可以用 [FreeFileSync][] 的 RealtimeSync， 也是一样，有变动 generate 一下
                                                                                
* 关于 preview. 你可以使用 [supervisor][] 后台管理。配合上面一点，那么你可以专心地编辑你自己的 wiki 了。

以上说的 Win 下没测试过，我是 Mint16

---

@tankywoo  Pelican 的做法是这样的 [site-generation](http://docs.getpelican.com/en/3.5.0/publish.html#site-generation)

Normally you would need to run make regenerate and make serve in two separate terminal sessions, but you can run both at once via:

    make devserver

The above command will simultaneously run Pelican in regeneration mode as well as serve the output at http://localhost:8000. Once you are done testing your changes, you should stop the development server via:

    ./develop_server.sh stop



[FreeFileSync]: http://sourceforge.net/projects/freefilesync                    
[supervisor]:  http://supervisord.org/ 
[pyinotify]: https://github.com/seb-m/pyinotify 
[supervisor]:  http://supervisord.org/

**Comment by jptiancai** [comment]
@lord63  :+1:  多谢,希望此功能可以simiki项目中,这样看下来感觉是需要借外力才能跑爽的项目. :smile:

**Comment by tankywoo** [comment]
@lord63 最开始我写过一个比较简陋的wiki时，也是用的inotify监控文件系统变化来自动更新。后来重写后这块没加进去。

@lord63 @jptiancai Pelican的那个我参考下看看。有个实时更新的是很方便的。

**Comment by jptiancai** [comment]
Pelican?能否给个链接？

**Comment by tankywoo** [comment]
@jptiancai 

lord63 给的那个链接

**Comment by Xuanwo** [comment]
Any update?
This issues can be closed now ~

**Comment by tankywoo** [comment]
@Xuanwo closed
