### ISSUE TITLE
目录名与 url 分离

### ISSUE THREAD

**Issue by MForever78** [tankywoo/simiki#37]
目前的状况是使用目录文件夹的名字作为 url 和 目录名，导致的问题是如果想要使用中文目录名的话会对 url 不友好。是否考虑将目录名与 url 分离。

**Comment by tankywoo** [comment]
这个功能的添加本身不是很麻烦，不过我暂时不会这么去做，因为这样会增加配置的复杂性(我还是希望能越简单约好，也许后期会考虑，不过目前还是把这个需求作为一个可二次开发的地方留给大家)。

如果有可能，我建议目录/文件名都使用英文比较好。

**Comment by MForever78** [comment]
了解。

记录一下我的做法，以防其他人和我有一样的问题。按照 @tankywoo 的想法，目录名最好使用英文，但文章名仍然可以使用英文。具体做法是：目录文件夹下的 .md 文件使用英文命名，而在 yaml 头里 title 字段指定中文标题。

@tankywoo 我理解你的想法。其实我觉得 URL 里不一定非要体现 category 吧。直接 example.com/somepost 这样岂不是更简洁？然后点进某个 category 的时候，用 example.com/somecategory 这样的 url ，单列出这一目录下所有的 posts。Category 也只须在 yaml 头里指定，而不需要通过目录结构来实现。

只是谈谈自己的想法，仅供参考。

**Comment by tankywoo** [comment]
@MForever78 :+1: 

针对URL, 这个方式也可以，其实和现有方式类似，只是输出布局的不同；

如果category在yaml头指定，这个是输入层，我的本意是按目录存放，即源文件结构明了。如果全存在一起，就和现有如Jekyll, Pelican没区别了。
