### ISSUE TITLE
关于markdown 自动生成目录。

### ISSUE THREAD

**Issue by BigAN** [tankywoo/simiki#38]
看到tankywoo的页面能讲markdown 的标题自动生成目录在右上角。这个feature可否加入到simiki啊。

**Comment by tankywoo** [comment]
默认就支持 TOC

    ---
    title: "Getting Started"
    layout: page
    date: 2099-06-02 00:00
    ---
    
    [TOC]   <--- header下面加入一行这个，即可自动生成TOC
    
    
    ....

**Comment by BigAN** [comment]
多谢！ 我在微博上也有问过你，麻烦。

**Comment by tankywoo** [comment]
@BigAN 不客气 ：）
