### ISSUE TITLE
生成output文件时会覆盖

### ISSUE THREAD

**Issue by zhaochunqi** [tankywoo/simiki#41]
Hi,在使用`simiki generate`时，会全部重新生成output下的文件，这样就不能单独deploy `gh-pages`分支，每次都要重新init，添加remote提交，请问有什么解决方案吗？

**Comment by tankywoo** [comment]
:+1:  感谢你的反馈，这个错误很严重；测试时忽略了github pages这块。

临时修复：

找到simiki python包的目录

    python -c 'import simiki; print simiki.__file__'

然后在此文件目录中编辑`cli.py`, 注释或删除以下两行(v1.4下是105,106行):

        if os.path.exists(dest_dir):
            emptytree(dest_dir)

代码我这两天修复下

**Comment by Xuanwo** [comment]
原来这个是BUG。。一直以来，我都是用脚本来搞的。。

**Comment by zhaochunqi** [comment]
Thanks . 修改后工作的很好。
其实可以参考`hexo`的部署方式，有时间我提交个`pull request`吧。
