### ISSUE TITLE
目录名字过长时,与文章列表有重叠

### ISSUE THREAD

**Issue by x-hansong** [tankywoo/simiki#43]
![2015-09-23 11 54 10](https://cloud.githubusercontent.com/assets/5747697/10037524/f82b1c24-61e9-11e5-9b14-da4ccb6b15fc.png)

**Comment by tankywoo** [comment]
这个是主题的问题。

修改`style.css`中:

    #container .category h2 {
        color: #CCC;
    }

改为:

    #container .category h2 {
        color: #CCC;
        word-wrap: break-word;
    }

**Comment by x-hansong** [comment]
谢谢,我用的是yasimple主题.麻烦修复一下主题代码.

**Comment by tankywoo** [comment]
@x-hansong 恩，感谢提醒 :+1: 。后续有yasimple的问题，可以在这里提issue https://github.com/tankywoo/yasimple
