### ISSUE TITLE
支持站点地图

### ISSUE THREAD

**Issue by Xuanwo** [tankywoo/simiki#44]
感觉可以支持一下自动生成atom.xml之类的以便于支持RSS订阅和站点地图~

**Comment by tankywoo** [comment]
这块我也想过. 不过对于博客或其它文章类的, 因为一篇文章写出来后就成型了，后期基本不会动, 所以适合订阅.

对于wiki，应该更多的是后期一直更新. 不知道这样是否适合rss

我得抽时间了解下这块的协议和内容, 看看能处理哪些.

你也可以给出一些想法或者建议 :+1:

**Comment by Xuanwo** [comment]
我的想法是不用加入条目的具体内容，只要包含拥有的条目即可。
这样的话，不管是调用Google或者自己实现站内搜索都会比较方便~

**Comment by tankywoo** [comment]
@Xuanwo Good, 我这两天研究下 :+1:

**Comment by Xuanwo** [comment]
@tankywoo 辛苦~

**Comment by tankywoo** [comment]
@Xuanwo 今天看了下相关的规范，可以把这个弄出来。

后续应该可以通过google搜索或者基于feed来写搜索都行。

下周抽时间把atom先写出来。

**Comment by tankywoo** [comment]
feed已经支持了，见 [simiki - feed](http://simiki.org/zh-docs/faq.html#feed)；这个issue先关闭了。
