### ISSUE TITLE
启动 simiki 报 failed to create process.

### ISSUE THREAD

**Issue by nopyhe** [tankywoo/simiki#45]
python3.5 on windows10.

pip 安装依赖的时候遇到了问题，是  pyyaml 和 PyCrypto
下载的第三方编译：

pyyaml: http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyyaml
PyCrypto: https://github.com/sfbahr/PyCrypto-Wheels

然后终于把 simiki 装好了……
然而……cmd 运行 ``simiki``报 ``failed to create process.``

**Comment by tankywoo** [comment]
抱歉, Simiki 暂时不支持Python 3.x；建议在Python 2.7下使用 :sob:

**Comment by nopyhe** [comment]
嗯……这个最好在 readme.md 中说一下吧……

还有 http://simiki.org/zh-docs/faq.html 这里说 要安装 ``ecsda``，这个好像拼错了 应该是 ``ecdsa``?

**Comment by tankywoo** [comment]
恩，稍后我加入到README

faq那里确实拼错了，感谢提醒 :+1:

**Comment by tankywoo** [comment]
hi, @nopyhe , Simiki最近版本1.5.0-1已经支持Python3.x >= 3.3, 你可以再试试 :smile:

**Comment by Xuanwo** [comment]
Simiki 现在在3.4上工作的情况不错，只是主题需要做一些调整，这个可以加到Doc中去。
同时，这个Issue已经可以关闭了～

**Comment by tankywoo** [comment]
@Xuanwo 主要需要做一些调整是指？

**Comment by Xuanwo** [comment]
Ref: https://github.com/tankywoo/simiki/issues/54#issuecomment-180383547

官方上已经改了，但是有的人可能之前就下载了一直没有更新，建议加到FAQ

**Comment by tankywoo** [comment]
@Xuanwo 恩，感谢提醒 👍
