### ISSUE TITLE
fabfile.py 163和169行的正则有遗漏

### ISSUE THREAD

**Issue by ferstar** [tankywoo/simiki#52]
[L163](https://github.com/tankywoo/simiki/blob/master/simiki/conf_templates/fabfile.py#L163)这里会漏掉两种情况：
```
# 1. 有文件被删除 git status --porcelain命令结果前两位字符应该是
空格+D
# 2. 新添加的文件没有被追踪 git status --porcelain 输出前两位字符是
??
# 3. 有文件被修改
空格+M
```
需要稍微修改下正则，匹配到前两种情况
`res = local('git status --porcelain 2>/dev/null | egrep \'^ [DM]|^\?\?\' | wc -l', capture=True)`

然后检测到有改动执行`git add -A`后
[L169](https://github.com/tankywoo/simiki/blob/master/simiki/conf_templates/fabfile.py#L169)这里会漏掉三种情况
```
# 1. 文件被重命名
R+空格
# 2. 文件被删除
D+空格
# 3. 有新文件
A+空格
# 4. 文件被修改
M+空格
```
需要修改下正则，匹配到前三种情况
`res = local('git status --porcelain 2>/dev/null | egrep \'^[ADMR]\' | wc -l', capture=True)`

**Comment by tankywoo** [comment]
这块我需要再想想，之前是只提交`Tracked`的文件，并且只简单考虑了`Modified`的文件。后来我改为提交所有文件，则又复杂了许多。

一方面，这种简化的操作，很容易使操作者把一些不该提交的文件加入进来，容易出现安全事故。所以我最初只是想手动把想要的文件加入到Git库。

并且按照`porcelain`的状态，可能的情况比你列出的还要多一些 :cry: ，比如rename的文件，比如已经add的文件等。

**Comment by ferstar** [comment]
@tankywoo 我闲的蛋疼把`porcelain`可能的状态都测试过，应该就是这么些情况。

至于安全事故，看来是我太狭隘，只管自己独乐乐。

其实我在本地`fabfile.py`还加了更懒的方法，直接`fab cd`后自动生成静态页面并提交 master 和 gh-pages 分支。

**Comment by tankywoo** [comment]
@ferstar L163这块，比如还有Rename(R)，以及Stage(A)等的情况；

具体我过几天才能确定，这几天忙着准备些东西回家了

**Comment by ferstar** [comment]
@tankywoo 这些情况实际上的表现是这样的

```
# 这里模拟一个 git rep 目录
➜  xx git:(master) mv 1 4 
# 如果仅用 mv，产生的效果这里是被分解成两步操作
➜  xx git:(master) ✗ git status --porcelain
 D 1
?? 4
➜  xx git:(master) ✗ git checkout .
➜  xx git:(master) ✗ ls
1  2  3  4
➜  xx git:(master) ✗ git status --porcelain 
?? 4
➜  xx git:(master) ✗ rm 4
# 使用 git mv 结果就成 L169 中的情况了
➜  xx git:(master) git mv 1 4
➜  xx git:(master) ✗ git status --porcelain 
R  1 -> 4

```

希望我把问题说清楚了，囧rz。

**Comment by tankywoo** [comment]
Hi, @ferstar ，今天才有时间好好想下这块。

这块我之前记错了，你之前说的没有问题。这里我也改了很多，首先还是去掉了untracked文件的自动add，最初就是这样的，untracked的文件交由用户自己选择add。

另外，使用`git diff`更容易区别work tree和index，而不需要再去判断`--porcelain`复杂的输出.

具体我在commit message里提到了，你可以看看，也可以看看功能上还有没有遗漏的 :smile: 

最后感谢你的支持和建议 :+1:

**Comment by tankywoo** [comment]
@ferstar Hi, 这个Issue现在还有问题吗？如果没问题我就Close了。

**Comment by ferstar** [comment]
@tankywoo 没啥问题了，我用着挺好，再次感谢你的 simiki :+1:
