### ISSUE TITLE
是否能加入favicon显示？

### ISSUE THREAD

**Issue by ferstar** [tankywoo/simiki#53]
> 好吧，我承认是有点强迫症了，在`simiki p`预览页面时发现`"GET /favicon.ico HTTP/1.1" 404 -`……

目前我是这么改的：https://github.com/ferstar/simiki/commit/1c5655f884d481093502b1e91c54ea992469a74c

然后就可以把 favicon.ico 推送到 gh-pages 上面。不过这个方法看上去略挫，希望 @tankywoo 能做个高大上的解决方案出来。

**Comment by tankywoo** [comment]
暂时没有什么好的办法，因为目前的实现对所有文件把控比较严格，已知的文件才会选择放到output下。

这块我还在考虑中，可能会在下个版本对generator大改，放开这里的管控；也或者会改为配置文件来管理这些。

你的那个修改，可以把CNAME和favicon写到一个元组/列表，然后for循环做copy，减少冗余代码。你可以把这块改下，欢迎提一个PR :smile: 

P.S 其实favicon这个问题我是知道的，但是每次想起来，过后就忘了...

**Comment by tankywoo** [comment]
晚上有点时间，就顺手给支持了

**Comment by ferstar** [comment]
哈，支持了就好，此 issue 可关。
