### ISSUE TITLE
help 关于simiki g 对md文档自动转换

### ISSUE THREAD

**Issue by zzvv** [tankywoo/simiki#55]
gitbook的体验太烂

遂直接在content 目录放入了一个gitbook库,

执行`simiki g `

毋庸质疑error

看报错信息,应该是在匹配每个文件开头的
```
---
layout: page
title: ""
date: 
---
```

如果md文档中没包含即error
不知是否有其他技巧批量添加？

**Comment by Xuanwo** [comment]
Sublime大法好，`search in files`

**Comment by zzvv** [comment]
直接加入文件夹，然后search file.然后定位文件开头,录入？

By zzcv
On 周六, 2月 20, 2016 at 18:16, 漩涡 <notifications@github.com> wrote:
Sublime大法好， search in files

—
Reply to this email directly or view it on GitHub
[https://github.com/tankywoo/simiki/issues/55#issuecomment-186564671] .[https://github.com/notifications/beacon/ALZvwR7nLVdbQRnBsyVjooljwPu4iPvaks5pmDRpgaJpZM4HelSj.gif]

**Comment by tankywoo** [comment]
你好，我没用过gitbook，发一篇gitbook的md源文件格式看看？

**Comment by zzvv** [comment]
其实就是一篇普通的md，只是没私密simiki new的开头

By zzcv
On 周六, 2月 20, 2016 at 18:34, Tanky Woo <notifications@github.com> wrote:
你好，我没用过gitbook，发一篇gitbook的md源文件格式看看？

—
Reply to this email directly or view it on GitHub
[https://github.com/tankywoo/simiki/issues/55#issuecomment-186566089] .[https://github.com/notifications/beacon/ALZvwW9MxLtlA95zPVZyIZ7Kl1hBjOvyks5pmDirgaJpZM4HelSj.gif]

**Comment by Xuanwo** [comment]
@zzvv 是的，只是一个普通的批量文本替换操作而已，很多编辑器都能做到。

**Comment by zzvv** [comment]
感谢！ @Xuanwo  @tankywoo

**Comment by zzvv** [comment]
感谢！ @Xuanwo  @tankywoo

**Comment by zzvv** [comment]
感谢！ @Xuanwo  @tankywoo
