### ISSUE TITLE
More Infomation about simiki api

### ISSUE THREAD

**Issue by Xuanwo** [tankywoo/simiki#56]
Hello, I'm doing some work to add disqus into simiki, but I found there is no enough api for me to use.
For example, the url for current page, the identifier for an article.
And can I get the title for page with `page.title` ?

I get all the info from http://simiki.org/docs/variables.html and http://simiki.org/docs/metadata.html .
Please let me know if I missed anything.

**Comment by Xuanwo** [comment]
Now, I form the url in this way :`{{ site.url }}/{{ page.category }}/{{ page.title }}`

**Comment by tankywoo** [comment]
@Xuanwo Hi, Did you use it in page.html, or index.html ?

**Comment by Xuanwo** [comment]
Yes, I thought I can use them like {{ site.name }}.

Tanky Woo <notifications@github.com>于2016年2月27日 周六 15:15写道：

**Comment by tankywoo** [comment]
@Xuanwo page.title only exists in page.html

**Comment by Xuanwo** [comment]
Well, I got it, I will again~

Tanky Woo <notifications@github.com>于2016年2月28日周日 下午1:21写道：

**Comment by tankywoo** [comment]
@Xuanwo Did you solve this problem?

**Comment by Xuanwo** [comment]
Until now, no. Because I'm busy these days. I'm will try it later~

Tanky Woo <notifications@github.com>于2016年2月29日 周一 15:02写道：

**Comment by Xuanwo** [comment]
Done.

Modify these files.

## base.html

```jinja
<div id="container">
    {% block container %}
    {% endblock %}
    {% block disqus %}
    {% endblock %}
</div>
```

## page.html

```jinja
{% block disqus %}
<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
var disqus_config = function () {
	this.page.url = "{{ site.url }}{{ site.root }}/{{ page.category }}/{{ page.title }}"; // Replace PAGE_URL with your page's canonical URL variable
	this.page.identifier = "{{ page.title }}" ; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//clicookbook.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
{% endblock %}
```

@tankywoo Hope this will be helpful. Maybe I can add it to the doc.

**Comment by tankywoo** [comment]
@Xuanwo Cool，Maybe you can move disqus outside of `<body>` for better

**Comment by Xuanwo** [comment]
`<div id="disqus_thread"></div>` this should be in <container> , and the js should be the end of the <body>

**Comment by tankywoo** [comment]
@Xuanwo right 👍
