### ISSUE TITLE
支持Mathjax

### ISSUE THREAD

**Issue by wddoer** [tankywoo/simiki#58]
如果能支持Mathjax就更好了

**Comment by tracholar** [comment]
这个很容易啊，你直接修改模板文件就可以了，导入js就可以用了

**Comment by tankywoo** [comment]
你好，我对Mathjax也不太了解，看了下官网也少，本质是一个JS库。

所以这个应该是不需要Simiki本身去支持，主题上`base.html`增加这个JS库的引入，然后markdown文件直接写就行了，Mathjax会自动转换。

我本地也试了下，是ok的。

**Comment by wddoer** [comment]
谢谢，确实如此~

**Comment by tankywoo** [comment]
@wddoer 好的，那我关闭Issue了。有问题欢迎随便提Issue。
