### ISSUE TITLE
怎么实现内链？

### ISSUE THREAD

**Issue by tracholar** [tankywoo/simiki#59]
我想问一下，目前有什么方便的办法在md中添加内链么？我目前是把它当做普通链接添加，如果能够实现像wikipedia那样内链编写方式就好了。

**Comment by tankywoo** [comment]
我看了下维基百科的内链，是这种格式`[[Python]]` ？

**Comment by tracholar** [comment]
是的，主要是在写作的时候方便，而且日后如果目录变更了也不用修改。

**Comment by tankywoo** [comment]
@tracholar 👍  

这个应该是可以实现的，我需要看看Markdown引擎的文档，确认下是否可以扩展。

**Comment by tracholar** [comment]
另外对图片的链接也可以考虑一下，wiki图片编辑方式是这样的`[[File:wiki.png]]`，可以只实现简单的添加
图片的功能，这应该比手动输入Markdown方式图片方便得多。

这个项目不错，点个赞，可惜现在忙着毕业，如果毕业后有空，看能不能也贡献点代码。

**Comment by tracholar** [comment]
如果markdown引擎不能扩展，应该也可以通过增加一个预处理模块实现。将标记转为html就可以了，
然后再传给引擎解析。因为markdown是支持html标签的。

**Comment by tankywoo** [comment]
@tracholar 是的，预处理还有个好处就是不需要依赖于第三方Markdown引擎的支持。刚本地试了下当前Markdown引擎对于扩展的支持，也还不错。

近期会发布一个Release，这个特性预计会在下一个版本加上，我需要考虑下标记的选择以及具体的实现。挺实用的一个功能 👍

**Comment by wangkaixianmml** [comment]
新手一枚，我想问的问题如下：
http://localhost:8000/python/jinja2.html
我如何在jinja2.html中加入链接，指向下一层目录，或者说能不能再有下一级目录。

**Comment by tankywoo** [comment]
@wangkaixianmml 你好，如果问题和当前Issue没有关联性，请新开一个Issue。

**Comment by iceboal** [comment]
希望在此基础上考虑对自定义扩展的支持，比如自定义
`[[Wikipedia:Water|water]]`生成为`[water](https://en.wikipedia.org/wiki/Water)`或直接外链到wikipedia。
或`[[Javadoc:java.lang.Object]]`生成`[Object](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html)`
不过可能不是一个普遍的需求。

**Comment by Xuanwo** [comment]
@tankywoo ref: https://pythonhosted.org/Markdown/extensions/wikilinks.html

我们依赖的 Markdown 已经原生支持了，可以考虑一下升级 Markdown 依赖。
