### ISSUE TITLE
Could not listen on port 8000

### ISSUE THREAD

**Issue by toastsgithub** [tankywoo/simiki#60]
mac os
python 2.7.11

-------------------
昨晚刚刚安装了，写了两篇（感觉很棒），但今早一跑 simiki p就提示Could not listen on port 8000
①用lsof -i:8000检查了端口没有被占用
②在配置文件里配置了debug模式为true 但在preview这一步上除了以上的那条外没有更多的提示信息

本人Python小白一枚，查看源码只看懂了是捕捉到了OSError 或IOError @-@
望作者能给予帮助

谢谢

**Comment by tankywoo** [comment]
你好。

因为当前8000端口无法使用，所以才会报这个。

可以先确认下是否还有simiki的进程(`ps aux | grep simiki`)

**Comment by toastsgithub** [comment]
你好刚刚我使用了那个指令查询和simiki相关的进程但显示只有 grep这个进程

~~~~
username      944   0.0  0.0  2432792    576 s000  R+   11:09AM   0:00.00 grep simiki
~~~~

并且我尝试用simiki p --port 8001更换监听端口，它也给了同样的**[ERROR]: Could not listen on port 8001**的提示,更换多个未占用port也是同样的结果😢

**Comment by tankywoo** [comment]
@toastsgithub 

尝试SimpleHTTPServer:

    python -m SimpleHTTPServer

以及(mac下)：

    nc -l 8000

确认是否都能监听？

**Comment by toastsgithub** [comment]
能的（吧？）
第一个指令的响应是：

~~~~
Serving HTTP on 0.0.0.0 port 8000 ...
~~~~

第二个指令没有任何提示

**Comment by tankywoo** [comment]
@toastsgithub 你可以按这个diff 63888fa80f74c09cefe670ff58df0be7a92b5340 本地改下源码 `simiki/server.py` ，输出一些详细信息并贴出来。之前我也没遇到过这种情况。

通过下面这条命令找到simiki源码目录：

    python -c 'import simiki; print(simiki.__path__)'

**Comment by toastsgithub** [comment]
输出信息如下

----

![image](https://cloud.githubusercontent.com/assets/11254241/15643050/b3571ad6-267d-11e6-8770-b8be5989fa67.png)

**Comment by tankywoo** [comment]
额，执行下：

     ping localhost  # 或者 host localhost

确认下`localhost`是否可以解析（正常情况是在`/etc/hosts`中定义）。感觉像是localhost无法解析造成，因为我这边默认是bind到localhost。如果是这个问题，那我得考虑改为'127.0.0.1'了。

**Comment by toastsgithub** [comment]
①localhost 是ping不通的但是这个问题是一直存在，至少在使用simiki之前也是ping不通的，这点可以确认，奇怪的是在这样的情况下（昨天一整晚）还是能成功运行simiki。

②用host localhost 有以下输出

~~~~
localhost has address 127.0.0.1
localhost has IPv6 address ::1
~~~~

**Comment by tankywoo** [comment]
有解析，但是ping不通。你执行`ifconfig -a` 或者 `ip a` 截图我看下。我感觉你的 `loopback(lo)` 口宕了。

**Comment by toastsgithub** [comment]
## 回到宿舍无意发现localhost能ping通，接着simiki也能正常运行，接着我重新做了几个测试

### ①在宿舍使用自己的路由器无线接入，能ping通，能preview

![private_with_wifi](http://o7y72af29.bkt.clouddn.com/in_private_with_wifi.png)

### ②关闭网络，不能ping通，不能preview

![without_wifi](http://o7y72af29.bkt.clouddn.com/without_wifi.png)

### ③在公共环境下，通过无线路由器（由网络中心配置）接入无线网，不能Ping通，不能review

![in_public](http://o7y72af29.bkt.clouddn.com/inpub.png)

----

大致来说  ：就是ping不通的时候就运行不了了，具体是什么样的配置导致我在某些环境下能ping通有的又不能，还没搞清楚，不过如果没有别的方面的考虑，您还是可以考虑下默认用127.0.0.1代替localhost

**Comment by tankywoo** [comment]
@toastsgithub 断开网络的情况下，是不会影响loopback口的。而且我看你的三个截图，lo0都是UP且RUNNING的

你可以贴下你的`/etc/hosts`配置吗（主要是localhost对应的ip）？我感觉你本地是不是用了一些hosts工具，改了/etc/hosts文件。

另外，localhost这个我确实需要改下，直接写为`127.0.0.1`

**Comment by toastsgithub** [comment]
恩 hosts中所有关于localhost的配置如下


![image](https://cloud.githubusercontent.com/assets/11254241/15651755/0bded5aa-26b4-11e6-933b-79059d21ebc8.png)


----

 ping 127.0.0.1在上述三种情况下都是通的

**Comment by tankywoo** [comment]
@toastsgithub 比较奇怪了，想不到哪个地方可以在网络断掉的时候，修改localhost的记录并影响到解析。

目前使用的话，你可以先将源码下`simiki/cli.py`的第30行，`Bind host to preview [default: localhost]` 改为`Bind host to preview [default: 127.0.0.1]`，以解决你目前的问题。过些天我会发布一个版本，顺便处理这个。

另外，这个问题的表象已经解决了，深层次的问题没法实际去排查，所以就先关闭这个Issue了，感谢你的支持，后续还有问题，欢迎随时提出来 👍

**Comment by toastsgithub** [comment]
好的 也感谢你的耐心解答，很棒的东西，很喜欢 ， 会持续关注的

**Comment by tankywoo** [comment]
@toastsgithub Sorry，上面说错了，没必要去改代码了，preview时直接加上`--host 127.0.0.1`就可以了：

    simiki p --host 127.0.0.1

**Comment by toastsgithub** [comment]
恩 手动测试了都可以运行的  因为写了些脚本运行simiki 就直接改source不一一修改脚本了
