### ISSUE TITLE
simiwi not found on linux after pip install simiki?

### ISSUE THREAD

**Issue by djstava** [tankywoo/simiki#61]
simiwi not found on linux after pip3 install simiki?

**Comment by tankywoo** [comment]
Hi, could you please paste your `pip3 install simiki` log？

In my localhost, it works ok:

```plain
(python34)tankywoo@gentoo /tmp % python -V
Python 3.4.3

(python34)tankywoo@gentoo /tmp % pip3 freeze | grep simiki
simiki==1.5.1

(python34)tankywoo@gentoo /tmp % simiki --version
Simiki 1.5.1
```

And, the right spelling is `simiki`, not `simiwi`...

**Comment by djstava** [comment]
`djstava@ThinkPad:~$ pip3 install simiki
Requirement already satisfied (use --upgrade to upgrade): simiki in ./.local/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): Pygments==1.6 in ./.local/lib/python3.5/site-packages (from simiki)
Requirement already satisfied (use --upgrade to upgrade): Markdown==2.4.1 in ./.local/lib/python3.5/site-packages (from simiki)
Requirement already satisfied (use --upgrade to upgrade): tzlocal==1.2 in ./.local/lib/python3.5/site-packages (from simiki)
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.11 in ./.local/lib/python3.5/site-packages (from simiki)
Requirement already satisfied (use --upgrade to upgrade): docopt==0.6.1 in ./.local/lib/python3.5/site-packages (from simiki)
Requirement already satisfied (use --upgrade to upgrade): ordereddict==1.1 in ./.local/lib/python3.5/site-packages (from simiki)
Requirement already satisfied (use --upgrade to upgrade): pytz==2015.7 in ./.local/lib/python3.5/site-packages (from simiki)
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.7.3 in ./.local/lib/python3.5/site-packages (from simiki)
Requirement already satisfied (use --upgrade to upgrade): watchdog==0.8.3 in ./.local/lib/python3.5/site-packages (from simiki)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in ./.local/lib/python3.5/site-packages (from Jinja2==2.7.3->simiki)
Requirement already satisfied (use --upgrade to upgrade): argh>=0.24.1 in ./.local/lib/python3.5/site-packages (from watchdog==0.8.3->simiki)
Requirement already satisfied (use --upgrade to upgrade): pathtools>=0.1.1 in ./.local/lib/python3.5/site-packages (from watchdog==0.8.3->simiki)
`

It seems that simiki is installed under ~/.local/bin (ubuntu 16.04 64bit,python3.5.1). And simiki works.

**Comment by tankywoo** [comment]
@djstava It seems that you used `pip` with `--user` option or others likely，this will install python packager under `$HOME/.local/`, and you should make sure `$HOME/.local/bin` is in you `$PATH` environment variable.

**Comment by djstava** [comment]
Yes,$PATH environment variable can solve this problem,thanks.

**Comment by tankywoo** [comment]
@djstava I will close this issue. If you have any problems, welcome to open a new issue.
