### ISSUE TITLE
主题可以在哪里下载的到？

### ISSUE THREAD

**Issue by holtenko** [tankywoo/simiki#63]
主题可以在哪里下载的到？

**Comment by tankywoo** [comment]
你好，<https://github.com/tankywoo/simiki-themes>

不过目前主题还比较少。

**Comment by holtenko** [comment]
YASimple_X2这个主题请问可以在哪里下载的到？我用yasimple好像collection和tag都不起作用

**Comment by tankywoo** [comment]
@holtenko collection和tag这个是simiki新版本支持，这两天我会release，并将yasimple_x2一起开源 😄

**Comment by tankywoo** [comment]
@holtenko simiki v1.6.0已发布，支持collection和tag，欢迎更新使用；另外yasimple_x2在 <https://github.com/tankywoo/yasimple_x2>

**Comment by holtenko** [comment]
Cool!
