### ISSUE TITLE
we could implement live preview with facebook watchman.

### ISSUE THREAD

**Issue by secwang** [tankywoo/simiki#65]
When I use simiki p to preview my wiki in broswer, found that watchman is great for auto generate wiki output. 

I write my script down here, not sure how to add it to this project , hope it will be helpful.

Have tested with OSX , and linux will work , cause facebook watchman is cross-platform.
```
brew install watchman 
cd mywiki
watchman-make -p 'content/**/*.md' --make=/usr/local/bin/simiki -t g
```

**Comment by secwang** [comment]
If we write little script combine generate and deploy , we do not need Travis CI any more XD.

**Comment by tankywoo** [comment]
simiki preview already support auto regenerate with `-w` option:

    simiki p -w

**Comment by secwang** [comment]
Oh, I did not notice this point. Thank you.
