### ISSUE TITLE
category 名称仅首字母大写

### ISSUE THREAD

**Issue by Ricky-Gong** [tankywoo/simiki#66]
即便在 content/ 目录下将 category 的名字设置为大小写混杂，生成出来的网页依旧仅首字母大写。不太美观。

请问这是网页生成过程中出的问题吗？

![image](https://cloud.githubusercontent.com/assets/8509855/16759920/f3a0014e-484b-11e6-872d-593e98b017a3.png)

![image](https://cloud.githubusercontent.com/assets/8509855/16759874/acd84e56-484b-11e6-9071-eaa0c8bca9b9.png)

**Comment by tankywoo** [comment]
打开wiki下`themes/simple2/index.html`文件，第17行，删除`|capitalize`，最后的显示为：

    {%- else %}{{ category.name}}{% endif %}

**Comment by Ricky-Gong** [comment]
可以了，谢谢！
