### ISSUE TITLE
为什么集合没有生效呢？

### ISSUE THREAD

**Issue by sunzy** [tankywoo/simiki#68]
在meta中加入了collection
但是用simiki g生成后，这篇wiki还是在原来的目录下，而不是目录下的collection里

**Comment by tankywoo** [comment]
simiki版本是多少？主题是用的哪个？

**Comment by sunzy** [comment]
查了下之前的版本是1.5的，现在升级到1.6后就好了

**Comment by tankywoo** [comment]
恩，集合是1.6后才支持的。 👍
