### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by fangmenghao** [tankywoo/simiki#69]
请问您一个问题：我的wiki部署在github上是Page not found
我的部署过程：
1. 先是在本地弄好了wiki目录
2. 我在主目录git init 然后推送到master分支上。
3. 然后通过fab deploy把output推送到gh-pages的分支上

但是为什么找不到页面。
我的网站地址：https://fangmenghao.github.io/
我的项目地址：https://github.com/fangmenghao/fangmenghao.github.io

**Comment by tankywoo** [comment]
你这个是Github的User Pages, output目录应该处于master分支，其它目录在source分支。

http://simiki.org/zh-docs/deploy.html 文档里有提到，另外你可以看看官方对Github Pages的介绍，你这个配法是针对Project Pages

**Comment by fangmenghao** [comment]
@tankywoo 
对，刚刚我改了，可以了。但是这个文档里Github Pages那个deploy的配置里写着默认是gh-pages我就以为那样也可以。
哦，对了。那个echo '*.pyc\noutput' > .gitignore，要把echo要加-e选项才能让\n有效。可能你有别名吧。只是提醒一下。
还是很感谢你。

**Comment by tankywoo** [comment]
文档里写的branch默认是gh-pages分支，因为project pages可以建立多个，使用可能会广一些。

> 那个echo '*.pyc\noutput' > .gitignore，要把echo要加-e选项才能让\n有效
感谢提醒，zsh下echo处理了`\n`，bash echo需要加`-e`，我稍后更新下文档。 👍
