### ISSUE TITLE
如何控制目录的排列顺序?

### ISSUE THREAD

**Issue by liuxigu** [tankywoo/simiki#70]
你好.

如题.
例如我创建了 A B C  三个文件夹,编译之后,访问首页 ,文件夹C的文章在最上,然后是A 、B。
我想让文件夹A里面的文章排在最上, 要怎么做?

还有 如何控制文件夹内文章的排序? 能否让文章按时间前后顺序排序?

**Comment by tankywoo** [comment]
目前目录和目录中的文章在首页都是按字母排序。

所以针对目录，如果想排序，可以更改目录名如 `1. A`, `2. B`, `3. C`

针对目录中的文章，后续可能会考虑加上可配置为按创建时间排序以及按修改时间排序的功能。

**Comment by liuxigu** [comment]
@tankywoo  感谢阁下的回答

**Comment by tankywoo** [comment]
@liuxigu 有问题欢迎随时提Issue；如果此Issue没问题我就关闭了。

**Comment by liuxigu** [comment]
没有啦  谢谢 @tankywoo
