### ISSUE TITLE
第一次用 Update 那里出错

### ISSUE THREAD

**Issue by maxcrave** [tankywoo/simiki#71]
第一次用  出错误 不知道怎么解决?

[root@localhost Desktop]# pip install simiki
Downloading/unpacking simiki
  Downloading simiki-1.6.0.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/simiki/setup.py) egg_info for package simiki
Downloading/unpacking Markdown==2.4.1 (from simiki)
  Downloading Markdown-2.4.1.tar.gz (279kB): 279kB downloaded
  Running setup.py (path:/tmp/pip_build_root/Markdown/setup.py) egg_info for package Markdown
Downloading/unpacking Pygments==1.6 (from simiki)
  Downloading Pygments-1.6.tar.gz (1.4MB): 1.4MB downloaded
  Running setup.py (path:/tmp/pip_build_root/Pygments/setup.py) egg_info for package Pygments
Downloading/unpacking Jinja2==2.7.3 (from simiki)
  Downloading Jinja2-2.7.3.tar.gz (378kB): 378kB downloaded
  Running setup.py (path:/tmp/pip_build_root/Jinja2/setup.py) egg_info for package Jinja2
    warning: no files found matching '_' under directory 'custom_fixers'
    warning: no previously-included files matching '_' found under directory 'docs/_build'
    warning: no previously-included files matching '_.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '_.pyc' found under directory 'docs'
    warning: no previously-included files matching '_.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '_.pyo' found under directory 'docs'
Downloading/unpacking PyYAML==3.11 (from simiki)
  Downloading PyYAML-3.11.zip (371kB): 371kB downloaded
  Running setup.py (path:/tmp/pip_build_root/PyYAML/setup.py) egg_info for package PyYAML
Downloading/unpacking docopt==0.6.1 (from simiki)
  Downloading docopt-0.6.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/docopt/setup.py) egg_info for package docopt
Downloading/unpacking ordereddict==1.1 (from simiki)
  Downloading ordereddict-1.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/ordereddict/setup.py) egg_info for package ordereddict
Downloading/unpacking watchdog==0.8.3 (from simiki)
  Downloading watchdog-0.8.3.tar.gz (83kB): 83kB downloaded
  Running setup.py (path:/tmp/pip_build_root/watchdog/setup.py) egg_info for package watchdog
    warning: no files found matching '_.h' under directory 'src'
Downloading/unpacking pytz==2015.7 (from simiki)
  Downloading pytz-2015.7-py2.py3-none-any.whl (476kB): 476kB downloaded
Downloading/unpacking tzlocal==1.2 (from simiki)
  Downloading tzlocal-1.2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/tzlocal/setup.py) egg_info for package tzlocal
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/lib64/python2.6/site-packages (from Jinja2==2.7.3->simiki)
Downloading/unpacking argh>=0.24.1 (from watchdog==0.8.3->simiki)
  Downloading argh-0.26.2-py2.py3-none-any.whl
Downloading/unpacking pathtools>=0.1.1 (from watchdog==0.8.3->simiki)
  Downloading pathtools-0.1.2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/pathtools/setup.py) egg_info for package pathtools
Downloading/unpacking argparse>=1.1 (from watchdog==0.8.3->simiki)
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Installing collected packages: simiki, Markdown, Pygments, Jinja2, PyYAML, docopt, ordereddict, watchdog, pytz, tzlocal, argh, pathtools, argparse
  Running setup.py install for simiki
    Installing simiki script to /usr/bin
  Running setup.py install for Markdown
    changing mode of build/scripts-2.6/markdown_py from 644 to 755
    Converting docs/siteindex.txt -> build/docs/siteindex.html
    Converting docs/release-2.3.txt -> build/docs/release-2.3.html
    Converting docs/release-2.0.1.txt -> build/docs/release-2.0.1.html
    Converting docs/index.txt -> build/docs/index.html
    Converting docs/release-2.2.1.txt -> build/docs/release-2.2.1.html
    Converting docs/change_log.txt -> build/docs/change_log.html
    Converting docs/release-2.0.txt -> build/docs/release-2.0.html
    Converting docs/reference.txt -> build/docs/reference.html
    Converting docs/authors.txt -> build/docs/authors.html
    Converting docs/release-2.2.0.txt -> build/docs/release-2.2.0.html
    Converting docs/release-2.0.2.txt -> build/docs/release-2.0.2.html
    Converting docs/cli.txt -> build/docs/cli.html
    Converting docs/release-2.1.1.txt -> build/docs/release-2.1.1.html
    Converting docs/test_suite.txt -> build/docs/test_suite.html
    Converting docs/install.txt -> build/docs/install.html
    Converting docs/release-2.1.0.txt -> build/docs/release-2.1.0.html
    Converting docs/release-2.4.txt -> build/docs/release-2.4.html
    Converting docs/extensions/nl2br.txt -> build/docs/extensions/nl2br.html
    Converting docs/extensions/code_hilite.txt -> build/docs/extensions/code_hilite.html
    Converting docs/extensions/abbreviations.txt -> build/docs/extensions/abbreviations.html
    Converting docs/extensions/smart_strong.txt -> build/docs/extensions/smart_strong.html
    Converting docs/extensions/index.txt -> build/docs/extensions/index.html
    Converting docs/extensions/footnotes.txt -> build/docs/extensions/footnotes.html
    Converting docs/extensions/sane_lists.txt -> build/docs/extensions/sane_lists.html
    Converting docs/extensions/extra.txt -> build/docs/extensions/extra.html
    Converting docs/extensions/admonition.txt -> build/docs/extensions/admonition.html
    Converting docs/extensions/fenced_code_blocks.txt -> build/docs/extensions/fenced_code_blocks.html
    Converting docs/extensions/header_id.txt -> build/docs/extensions/header_id.html
    Converting docs/extensions/smarty.txt -> build/docs/extensions/smarty.html
    Converting docs/extensions/attr_list.txt -> build/docs/extensions/attr_list.html
    Converting docs/extensions/toc.txt -> build/docs/extensions/toc.html
    Converting docs/extensions/api.txt -> build/docs/extensions/api.html
    Converting docs/extensions/meta_data.txt -> build/docs/extensions/meta_data.html
    Converting docs/extensions/tables.txt -> build/docs/extensions/tables.html
    Converting docs/extensions/definition_lists.txt -> build/docs/extensions/definition_lists.html
    Converting docs/extensions/wikilinks.txt -> build/docs/extensions/wikilinks.html
    changing mode of /usr/bin/markdown_py to 755
  Running setup.py install for Pygments
    Installing pygmentize script to /usr/bin
  Running setup.py install for Jinja2
    warning: no files found matching '_' under directory 'custom_fixers'
    warning: no previously-included files matching '_' found under directory 'docs/_build'
    warning: no previously-included files matching '_.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '_.pyc' found under directory 'docs'
    warning: no previously-included files matching '_.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
  Running setup.py install for PyYAML
    checking if libyaml is compilable
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.6 -c build/temp.linux-x86_64-2.6/check_libyaml.c -o build/temp.linux-x86_64-2.6/check_libyaml.o
    build/temp.linux-x86_64-2.6/check_libyaml.c:2:18: error: yaml.h: No such file or directory
    build/temp.linux-x86_64-2.6/check_libyaml.c: In function ‘main’:
    build/temp.linux-x86_64-2.6/check_libyaml.c:5: error: ‘yaml_parser_t’ undeclared (first use in this function)
    build/temp.linux-x86_64-2.6/check_libyaml.c:5: error: (Each undeclared identifier is reported only once
    build/temp.linux-x86_64-2.6/check_libyaml.c:5: error: for each function it appears in.)
    build/temp.linux-x86_64-2.6/check_libyaml.c:5: error: expected ‘;’ before ‘parser’
    build/temp.linux-x86_64-2.6/check_libyaml.c:6: error: ‘yaml_emitter_t’ undeclared (first use in this function)
    build/temp.linux-x86_64-2.6/check_libyaml.c:6: error: expected ‘;’ before ‘emitter’
    build/temp.linux-x86_64-2.6/check_libyaml.c:8: warning: implicit declaration of function ‘yaml_parser_initialize’
    build/temp.linux-x86_64-2.6/check_libyaml.c:8: error: ‘parser’ undeclared (first use in this function)
    build/temp.linux-x86_64-2.6/check_libyaml.c:9: warning: implicit declaration of function ‘yaml_parser_delete’
    build/temp.linux-x86_64-2.6/check_libyaml.c:11: warning: implicit declaration of function ‘yaml_emitter_initialize’
    build/temp.linux-x86_64-2.6/check_libyaml.c:11: error: ‘emitter’ undeclared (first use in this function)
    build/temp.linux-x86_64-2.6/check_libyaml.c:12: warning: implicit declaration of function ‘yaml_emitter_delete’

```
libyaml is not found or a compiler error: forcing --without-libyaml
(if libyaml is installed correctly, you may need to
 specify the option --include-dirs or uncomment and
 modify the parameter include_dirs in setup.cfg)
```

  Running setup.py install for docopt
  Running setup.py install for ordereddict
  Running setup.py install for watchdog
    warning: no files found matching '*.h' under directory 'src'
    Installing watchmedo script to /usr/bin
  Running setup.py install for tzlocal
  Running setup.py install for pathtools
Successfully installed simiki Markdown Pygments Jinja2 PyYAML docopt ordereddict watchdog pytz tzlocal argh pathtools argparse
Cleaning up...

[root@localhost Desktop]# pip install -U simiki
Requirement already up-to-date: simiki in /usr/lib/python2.6/site-packages
Requirement already up-to-date: Markdown==2.4.1 in /usr/lib/python2.6/site-packages (from simiki)
Requirement already up-to-date: Pygments==1.6 in /usr/lib/python2.6/site-packages (from simiki)
Requirement already up-to-date: Jinja2==2.7.3 in /usr/lib/python2.6/site-packages (from simiki)
Requirement already up-to-date: PyYAML==3.11 in /usr/lib64/python2.6/site-packages (from simiki)
Requirement already up-to-date: docopt==0.6.1 in /usr/lib/python2.6/site-packages (from simiki)
Requirement already up-to-date: ordereddict==1.1 in /usr/lib/python2.6/site-packages (from simiki)
Requirement already up-to-date: watchdog==0.8.3 in /usr/lib/python2.6/site-packages (from simiki)
Requirement already up-to-date: pytz==2015.7 in /usr/lib/python2.6/site-packages (from simiki)
Requirement already up-to-date: tzlocal==1.2 in /usr/lib/python2.6/site-packages (from simiki)
Downloading/unpacking markupsafe from https://pypi.python.org/packages/c0/41/bae1254e0396c0cc8cf1751cb7d9afc90a602353695af5952530482c963f/MarkupSafe-0.23.tar.gz#md5=f5ab3deee4c37cd6a922fb81e730da6e (from Jinja2==2.7.3->simiki)
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py (path:/tmp/pip_build_root/markupsafe/setup.py) egg_info for package markupsafe
Requirement already up-to-date: argh>=0.24.1 in /usr/lib/python2.6/site-packages (from watchdog==0.8.3->simiki)
Requirement already up-to-date: pathtools>=0.1.1 in /usr/lib/python2.6/site-packages (from watchdog==0.8.3->simiki)
Requirement already up-to-date: argparse>=1.1 in /usr/lib/python2.6/site-packages (from watchdog==0.8.3->simiki)
Installing collected packages: markupsafe
  Found existing installation: MarkupSafe 0.9.2
    Uninstalling MarkupSafe:
      Successfully uninstalled MarkupSafe
  Running setup.py install for markupsafe
    building 'markupsafe._speedups' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.6 -c markupsafe/_speedups.c -o build/temp.linux-x86_64-2.6/markupsafe/_speedups.o
    markupsafe/_speedups.c:12:20: error: Python.h: No such file or directory
    markupsafe/_speedups.c:24: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘_’ token
    markupsafe/_speedups.c:26: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘_’ token
    markupsafe/_speedups.c: In function ‘init_constants’:
    markupsafe/_speedups.c:31: error: ‘PyObject’ undeclared (first use in this function)
    markupsafe/_speedups.c:31: error: (Each undeclared identifier is reported only once
    markupsafe/_speedups.c:31: error: for each function it appears in.)
    markupsafe/_speedups.c:31: error: ‘module’ undeclared (first use in this function)
    markupsafe/_speedups.c:33: error: ‘escaped_chars_repl’ undeclared (first use in this function)
    markupsafe/_speedups.c:33: warning: implicit declaration of function ‘PyUnicode_AS_UNICODE’
    markupsafe/_speedups.c:33: error: ‘PyUnicodeObject’ undeclared (first use in this function)
    markupsafe/_speedups.c:33: error: expected expression before ‘)’ token
    markupsafe/_speedups.c:34: error: expected expression before ‘)’ token
    markupsafe/_speedups.c:35: error: expected expression before ‘)’ token
    markupsafe/_speedups.c:36: error: expected expression before ‘)’ token
    markupsafe/_speedups.c:37: error: expected expression before ‘)’ token
    markupsafe/_speedups.c:40: warning: implicit declaration of function ‘memset’
    markupsafe/_speedups.c:40: warning: incompatible implicit declaration of built-in function ‘memset’
    markupsafe/_speedups.c:46: warning: implicit declaration of function ‘PyImport_ImportModule’
    markupsafe/_speedups.c:49: error: ‘markup’ undeclared (first use in this function)
    markupsafe/_speedups.c:49: warning: implicit declaration of function ‘PyObject_GetAttrString’
    markupsafe/_speedups.c:50: warning: implicit declaration of function ‘Py_DECREF’
    markupsafe/_speedups.c: At top level:
    markupsafe/_speedups.c:55: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘_’ token
    markupsafe/_speedups.c:117: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘_’ token
    markupsafe/_speedups.c:162: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘_’ token
    markupsafe/_speedups.c:171: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘_’ token
    markupsafe/_speedups.c:185: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘module_methods’
    markupsafe/_speedups.c: In function ‘init_speedups’:
    markupsafe/_speedups.c:213: warning: implicit declaration of function ‘Py_InitModule3’
    markupsafe/_speedups.c:213: error: ‘module_methods’ undeclared (first use in this function)
    ==========================================================================
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Failure information, if any, is above.
    Retrying the build without the C extension now.

```
==========================================================================
WARNING: The C extension could not be compiled, speedups are not enabled.
Plain-Python installation succeeded.
==========================================================================
```

Successfully installed markupsafe
Cleaning up...

[root@localhost Desktop]# simiki update
Traceback (most recent call last):
  File "/usr/bin/simiki", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 2603, in <module>
  File "/usr/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 666, in require
  File "/usr/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 565, in resolve
pkg_resources.DistributionNotFound: pytz==2015.7

这个是什么问题?

**Comment by tankywoo** [comment]
可能是pip有问题；如果是这个问题，你可以尝试其它通过pip安装的命令行工具，看看是否也报错。

另外可以参考[这个帖子](http://stackoverflow.com/questions/6200056/pip-broke-how-to-fix-distributionnotfound-error) 尝试修复下。

**Comment by 7anshuai** [comment]
遇到同样的问题：`pkg_resources.DistributionNotFound: pytz==2015.7`，更新 pip 到最新版本（`pip install --upgrade pip`）再重新安装 `pip install simiki` 报错：
```bash
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Collecting simiki
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading simiki-1.6.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'entry_points'
      warnings.warn(msg)
    /usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'include_package_data'
      warnings.warn(msg)
    /usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'test_suite'
      warnings.warn(msg)
    /usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'install_requires'
      warnings.warn(msg)
    /usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'tests_require'
      warnings.warn(msg)
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: invalid command 'egg_info'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1qPtOo/simiki/
```
再更新 `pip install --upgrade distribute` 之后就可以正常安装和使用 simiki

**Comment by Xuanwo** [comment]
@tankywoo This issue should be closed.

**Comment by tankywoo** [comment]
@7anshuai 看你的提示主要还是 python自身及相关组建比较旧导致。建议升级到 py2.7，后续 simiki 也会放弃在 py2.6 下的支持。

@Xuanwo 感谢提醒。
