### ISSUE TITLE
Feature Request: 多级目录，内部链接 & Web Console

### ISSUE THREAD

**Issue by Xuanwo** [tankywoo/simiki#72]
最近终于闲下来了，好好审视了一下自己对Wiki的需求，然后对着目前市面上的很多Wiki工具做了一下对比，认为Simiki还有以下功能值得去完善：
1. 多级目录的支持，个人的知识图谱必然是一个非线性非树状的一个复杂网络，两层目录实在是无法支持起日渐丰富的内容，所以我们需要一个多级目录的支持。
2. 内部链接。这个社区的朋友们也提到过，我觉得对于Wiki来讲，这是一个非常重要的功能，也是一个Wiki区别于传统博客的重大差异。在我的想象中，内部链接应该是基于关键词的，不会因为这个词条所处的位置发生变化。

> 可以考虑的功能：
> 
> Web Console。
> 经常出现的一种状况是有了一个Idea，但是手头并没有一个环境可以立马开始写，所以一个适配多种平台的Console就显得很有必要。

比较矛盾的一点是，我希望在保持Simiki尽可能简单的情况下实现这些必然会增加复杂度的功能，我猜我们需要一个好的PM :smile: 

@tankywoo 我们可以起草一个Readmap，将需求尽可能的分散以方便社区进行参与~

**Comment by tankywoo** [comment]
Hi, @Xuanwo 感谢你的建议 👍 

在做这个之前，我也用过其它的wiki和类似的产品，不过大部分都是围绕团队/协作的，所以功能也很多。而如你所说，Simiki围绕的是个人文档记录工具（个人Wiki），主旨是简单实用。

对于多级目录，这个最开始是支持的，但是在1.6.0版本时，我加入了集合的概念，于是砍掉了这块。对于一个多级目录，不管是代码层面，还是主题（模板层面），这两者都需要支持，多级结构的递归遍历都是一个很繁琐复杂的功能，可以参考第一款内置主题[simple](https://github.com/tankywoo/simiki/blob/master/simiki/themes/simple/index.html)的实现，其中使用了Jinja2的宏并作了递归。而且在个人使用以及查看其它使用者的情况，给我的感觉，两层结构应该已经是足够了，如果目录结构定义的过于复杂，是否可以考虑精简？这对个人的技能树也是一个整理规划。所以在目前没有一个完美的解决方案之前，暂时还是不考虑多级结构。

关于内部链接。包括你这里，以及之前的几个朋友，已经给出了关于这块很多不错的建议了。这个前阵子我已经开始着手了，不过刚起了一个头就暂时忙其它事情取了，后续会继续开发。

> 在我的想象中，内部链接应该是基于关键词的，不会因为这个词条所处的位置发生变化。

这个也是个非常好的tip！

> Web Console。
> 经常出现的一种状况是有了一个Idea，但是手头并没有一个环境可以立马开始写，所以一个适配多种平台的Console就显得很有必要。

临时记录用手机上的便签就可以了？

> 起草一个Readmap，将需求尽可能的分散以方便社区进行参与

readmap 是指 todos？

**Comment by Xuanwo** [comment]
笔误，Roadmap， 大体上就是让我们知道下一步的计划，有可能的话，我也想加入到开发中去 :smile:

**Comment by tankywoo** [comment]
@Xuanwo 👍  ToDo我到时加到README中

**Comment by ub3132003** [comment]
我就是觉得要把老文件全部加一个  front matter  的头好麻烦
