### ISSUE TITLE
fab deploy meets error in ghp-import 

### ISSUE THREAD

**Issue by wiekern** [tankywoo/simiki#74]
I just used command 'fab deploy' to deploy my wiki, but a error came.  From the error info it is something wrong with ghp-import. I have tried to solve it via google, but I was failed. I hope you guys can help me, thanks a lot!

[localhost] local: which ghp-import > /dev/null 2>&1; echo $?
[localhost] local: ghp-import -p -m "Update output documentation" -r origin -b gh-pages output
Counting objects: 116, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (88/88), done.
Writing objects: 100% (116/116), 33.11 KiB | 0 bytes/s, done.
Total 116 (delta 15), reused 114 (delta 13)
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
Traceback (most recent call last):
  File "/usr/local/bin/ghp-import", line 198, in <module>
    main()
  File "/usr/local/bin/ghp-import", line 194, in main
    sp.check_call(['git', 'push', opts.remote, opts.branch])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'gh-pages']' returned non-zero exit status 1

Fatal error: local() encountered an error (return code 1) while executing 'ghp-import -p -m "Update output documentation" -r origin -b gh-pages output'

Aborting.

**Comment by tankywoo** [comment]
Hello, that seems you can't push your commit to your remote repository.

You can give me more info with below:

* run command `git remote -v`
* display your **deploy** section in _config.yml
* your remote repository url

**Comment by wiekern** [comment]
I have pushed these files in "output/" directory manually, and it was successful.  Furthermore I have given the infos which you need as follow. 

1. 
➜  mywiki git:(gh-pages) ✗ git remote -v
origin	https://github.com/wiekern/wiki.git (fetch)
origin	https://github.com/wiekern/wiki.git (push)

2.
➜  mywiki git:(gh-pages) ✗ cat _config.yml
# Document:
# http://simiki.org/docs/configuration.html

url: http://wiekern.github.io
title: wiekern's WIKI
keywords:
description:
author: wiekern
root: /wiki/

default_ext: md
pygments: true
debug: false

deploy:
  - type: git
    remote: origin
    branch: gh-pages

3.
remote repository url: https://github.com/wiekern/wiki

**Comment by tankywoo** [comment]
Try to change your repo's url with **`git`** protocol instead of **`https`**.

```bash
git remote set-url --push origin git@github.com:wiekern/wiki.git
```

https require input username/password manually.

**Comment by wiekern** [comment]
Thank you! You are right. It works now.  I have changed my remote repo url without https as follow:
<pre><code>
➜  mywiki git:(master) git remote -v
origin	http://github.com/wiekern/wiki.git (fetch)
origin	http://github.com/wiekern/wiki.git (push)
</code></pre>

Closed this issue.

**Comment by tankywoo** [comment]
@wiekern http/https should be the same problem, did you really can push to remote?

**Comment by wiekern** [comment]
As you mentioned, I have changed "http" to "https", it is in order. I can not repeat this issue now.
I remember that I have deleted my local repository and initiated a new local repository with `git init && git pull`. Then everything is right.  It's weird.

 I added my configurations.
<pre><code>
1.
➜  mywiki git:(master) git remote -v
origin	http://github.com/wiekern/wiki.git (fetch)
origin	http://github.com/wiekern/wiki.git (push)

2.
➜  mywiki git:(master) cat _config.yml
# Document:
# http://simiki.org/docs/configuration.html

url: http://wiekern.github.io/wiki
title: wiekern's Wiki
keywords: Linux, Java, C/C++, Android, Web
description:
author: wieKern
root: /wiki/

default_ext: md
pygments: true
debug: false

deploy:
  - type: git
    remote: origin
    branch: gh-pages


There is no change in my wiki,  but I still ran `fab deploy`, I got this message
➜  mywiki git:(master) fab deploy
[localhost] local: which ghp-import > /dev/null 2>&1; echo $?
[localhost] local: ghp-import -p -m "Update output documentation" -r origin -b gh-pages output
Counting objects: 1, done.
Writing objects: 100% (1/1), 196 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 1 (delta 0)
To http://github.com/wiekern/wiki.git
   900b8ba..b863972  gh-pages -> gh-pages

Done.
</code></pre>

**Comment by wiekern** [comment]
I am aware of one point. It may caused by `.ssh/know_hosts` in which there  is no matched ssh item for remote repository.

**Comment by tankywoo** [comment]
`.ssh/know_hosts` only work with **git(ssh)** protocol, and not work if you use **http/https**.

From what your pasted:

> error: RPC failed; curl 18 transfer closed with outstanding read data remaining
> fatal: The remote end hung up unexpectedly
> fatal: The remote end hung up unexpectedly

It looks like the network problem.

However, if you write your wiki in your personal environment, I suggest to use `git` protocol instead of `http/https`.
