### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by meroco** [tankywoo/simiki#75]
error: could not create '/Library/Python/2.7/site-packages/markdown': Permission denied

Mac OS X 10.11.6 
Python 3.5.2

**Comment by tankywoo** [comment]
You can't install **python package** directly by `pip install <package>` without root permission.

There are two way to solve this problem:

* use virtualenv, then install python package(include simiki) in env;
* or run `pip install --user simiki` to install package under your home directory.

**Comment by meroco** [comment]
It works,Thanks!
