### ISSUE TITLE
大神您好，请问这样是安装成功了吗，总是找不到命令

### ISSUE THREAD

**Issue by xcy396** [tankywoo/simiki#77]
~ pip install simiki --user python
Collecting simiki
  Downloading http://mirrors.aliyun.com/pypi/packages/42/83/9d0095d762295d20d4bca9ab166c56ee445cc70d8a1286f9bab1ea97430c/simiki-1.6.0.1.tar.gz
Requirement already satisfied: python in /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
Requirement already satisfied: Markdown==2.4.1 in /Library/Python/2.7/site-packages (from simiki)
Requirement already satisfied: Pygments==1.6 in /Library/Python/2.7/site-packages (from simiki)
Requirement already satisfied: Jinja2==2.7.3 in /Library/Python/2.7/site-packages (from simiki)
Requirement already satisfied: PyYAML==3.11 in /Library/Python/2.7/site-packages (from simiki)
Requirement already satisfied: docopt==0.6.1 in /Library/Python/2.7/site-packages (from simiki)
Requirement already satisfied: ordereddict==1.1 in /Library/Python/2.7/site-packages (from simiki)
Requirement already satisfied: watchdog==0.8.3 in /Library/Python/2.7/site-packages (from simiki)
Collecting pytz==2015.7 (from simiki)
  Downloading http://mirrors.aliyun.com/pypi/packages/c0/28/973f0382c803b21734cd7e97e0590928148ee21b1cbe8f7fed8b506204fb/pytz-2015.7-py2.py3-none-any.whl (476kB)
    100% |████████████████████████████████| 481kB 39kB/s
Requirement already satisfied: tzlocal==1.2 in ./Library/Python/2.7/lib/python/site-packages (from simiki)
Requirement already satisfied: markupsafe in /Library/Python/2.7/site-packages (from Jinja2==2.7.3->simiki)
Requirement already satisfied: argh>=0.24.1 in /Library/Python/2.7/site-packages (from watchdog==0.8.3->simiki)
Requirement already satisfied: pathtools>=0.1.1 in /Library/Python/2.7/site-packages (from watchdog==0.8.3->simiki)
Installing collected packages: pytz, simiki
  Running setup.py install for simiki ... done
Successfully installed pytz-2015.7 simiki-1.6.0.1
➜  ~ simiki --version
zsh: command not found: simiki
➜  ~ pytz --version
zsh: command not found: pytz
➜  ~ simiki -v
zsh: command not found: simiki
➜  ~ mywiki
➜  mywiki simiki init
zsh: command not found: simiki
➜  mywiki ~
➜  ~ python --version
Python 2.7.10
➜  ~ pip install -U simiki --user python
Requirement already up-to-date: simiki in ./Library/Python/2.7/lib/python/site-packages
Requirement already up-to-date: python in /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
Requirement already up-to-date: Markdown==2.4.1 in /Library/Python/2.7/site-packages (from simiki)
Requirement already up-to-date: Pygments==1.6 in /Library/Python/2.7/site-packages (from simiki)
Requirement already up-to-date: Jinja2==2.7.3 in /Library/Python/2.7/site-packages (from simiki)
Requirement already up-to-date: PyYAML==3.11 in /Library/Python/2.7/site-packages (from simiki)
Requirement already up-to-date: docopt==0.6.1 in /Library/Python/2.7/site-packages (from simiki)
Requirement already up-to-date: ordereddict==1.1 in /Library/Python/2.7/site-packages (from simiki)
Requirement already up-to-date: watchdog==0.8.3 in /Library/Python/2.7/site-packages (from simiki)
Collecting pytz==2015.7 (from simiki)
  Downloading http://mirrors.aliyun.com/pypi/packages/c0/28/973f0382c803b21734cd7e97e0590928148ee21b1cbe8f7fed8b506204fb/pytz-2015.7-py2.py3-none-any.whl (476kB)
    100% |████████████████████████████████| 481kB 39kB/s
Requirement already up-to-date: tzlocal==1.2 in ./Library/Python/2.7/lib/python/site-packages (from simiki)
Requirement already up-to-date: markupsafe in /Library/Python/2.7/site-packages (from Jinja2==2.7.3->simiki)
Requirement already up-to-date: argh>=0.24.1 in /Library/Python/2.7/site-packages (from watchdog==0.8.3->simiki)
Requirement already up-to-date: pathtools>=0.1.1 in /Library/Python/2.7/site-packages (from watchdog==0.8.3->simiki)
Installing collected packages: pytz
Successfully installed pytz-2015.7
➜  ~ cd mywiki
➜  mywiki simiki init
zsh: command not found: simiki

**Comment by tankywoo** [comment]
你好. `pip install simiki --user python` 这个后面的python是什么意思? 这个用法和我所知道的有点不一样.

另外, `--user`表示安装下当前用户的`~/.local/`下，执行文件如我这边环境, 在`~/.local/bin`下，所以你需要把这个目录加到你的`$PATH`环境变量，否则只能通过完全路径指定来调用。

**Comment by xcy396** [comment]
大神，麻烦您了，我直接按您的主页教程也就是`pip install simiki`来安装的话，就报一个权限被拒绝的错误。然后我就来来回回安装卸载了好几次，现在直接安装的话会报很多类似下面的这个错误，并且安装失败：
('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pytz', '/var/folders/ts/qnjgct6j66d49yt8xgp82mt40000gn/T/pip-BiXSyb-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pytz', "[Errno 1] Operation not permitted: '/var/folders/ts/qnjgct6j66d49yt8xgp82mt40000gn/T/pip-BiXSyb-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pytz'")

我在google查找说采用'pip install simiki --user python'这样，可以安装成功了，但是怎么设置环境变量都不好使，找不到命令
➜  ~ pip install simiki --user
Collecting simiki
  Downloading http://mirrors.aliyun.com/pypi/packages/42/83/9d0095d762295d20d4bca9ab166c56ee445cc70d8a1286f9bab1ea97430c/simiki-1.6.0.1.tar.gz
Requirement already satisfied: Markdown==2.4.1 in /Library/Python/2.7/site-packages (from simiki)
Requirement already satisfied: Pygments==1.6 in /Library/Python/2.7/site-packages (from simiki)
Requirement already satisfied: Jinja2==2.7.3 in /Library/Python/2.7/site-packages (from simiki)
Requirement already satisfied: PyYAML==3.11 in /Library/Python/2.7/site-packages (from simiki)
Requirement already satisfied: docopt==0.6.1 in /Library/Python/2.7/site-packages (from simiki)
Requirement already satisfied: ordereddict==1.1 in /Library/Python/2.7/site-packages (from simiki)
Requirement already satisfied: watchdog==0.8.3 in /Library/Python/2.7/site-packages (from simiki)
Collecting pytz==2015.7 (from simiki)
  Downloading http://mirrors.aliyun.com/pypi/packages/c0/28/973f0382c803b21734cd7e97e0590928148ee21b1cbe8f7fed8b506204fb/pytz-2015.7-py2.py3-none-any.whl (476kB)
    100% |████████████████████████████████| 481kB 43kB/s
Requirement already satisfied: tzlocal==1.2 in ./Library/Python/2.7/lib/python/site-packages (from simiki)
Requirement already satisfied: markupsafe in /Library/Python/2.7/site-packages (from Jinja2==2.7.3->simiki)
Requirement already satisfied: argh>=0.24.1 in /Library/Python/2.7/site-packages (from watchdog==0.8.3->simiki)
Requirement already satisfied: pathtools>=0.1.1 in /Library/Python/2.7/site-packages (from watchdog==0.8.3->simiki)
Installing collected packages: pytz, simiki
  Running setup.py install for simiki ... done
Successfully installed pytz-2015.7 simiki-1.6.0.1
➜  ~ mywiki
➜  mywiki simiki init
zsh: command not found: simiki

我用的zsh，在'.zshrc'中设置为：
`export PATH=${PATH}:~/.local/bin`
或者
`export PATH=${PATH}:~/Library/Python/2.7/lib/python/site-packages/`
都提示`simiki`命令无效，还请大神再帮忙看下，谢谢！

**Comment by tankywoo** [comment]
刚注意到Mac下自带python针对`--user`的行为是将可执行程序放到`$HOME/Library/Python/2.7/bin/`下，你需要将这个加到`$PATH`中

**Comment by xcy396** [comment]
@tankywoo 已完美解决，感谢您的耐心解答～努力向您学习！
只是在安装时不加`--user`的话会提示的那个权限不足的状况，不知道是问题出在哪里，现在也无法重现了。

**Comment by tankywoo** [comment]
@xcy396 客气了，解决就好。 👍 有问题欢迎随时提issue，这个我先关闭了。
