### ISSUE TITLE
After install on Mac, simiki not found

### ISSUE THREAD

**Issue by meteor5118** [tankywoo/simiki#80]
On mac system, after install simiki:
```
# pip list | grep simiki
simiki (1.6.0.1)
# which simiki
simiki not found
```

**Comment by tankywoo** [comment]
@meteor5118 You can try run `pip uninstall simiki`, this will list all the installed files of simiki (and ask if you want make sure to uninstall them, enter 'n'). I guess the path of bin path is not in your `$PATH` environment variable, you can find the simiki bin file in the list files, and make sure the directory of it is in your `$PATH` variable.

**Comment by Xuanwo** [comment]
Upgrade pip to latest version could solve this problem.

@tankywoo This issue cloud be closed if no more update.

**Comment by tankywoo** [comment]
@Xuanwo which version of pip would cause this problem?

**Comment by Xuanwo** [comment]
@tankywoo I'm not sure, but I met the same problem on ubuntu 14.04 with python-pip, after upgrade pip, I fix this problem.

**Comment by tankywoo** [comment]
@Xuanwo 👍

**Comment by onelots** [comment]
Hum, I just had the error... I had to move /home/onelots/.local/bin/simiki to /bin/simiki but now it works...
