### ISSUE TITLE
fab deploy命令无法将本地修改内容push到远程仓库中

### ISSUE THREAD

**Issue by xroocky** [tankywoo/simiki#81]
Tanky Woo你好！非常感谢你为大家提供了如此方便易用的simiki框架：）
在仔细阅读过simiki文档后，我成功地搭建了我的个人wiki（部署在Github Pages），但是当我在尝试将本地修改的内容push到远程仓库时遇到了问题，错误日志如下：
``` bash
➜  Wiki git:(master) fab deploy
[localhost] local: which ghp-import > /dev/null 2>&1; echo $?
[localhost] local: ghp-import -p -m "Update output documentation" -r origin -b gh-pages output
To github.com:xroocky/rwiki.git
 ! [rejected]        gh-pages -> gh-pages (fetch first)
error: failed to push some refs to 'git@github.com:xroocky/rwiki.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Traceback (most recent call last):
  File "/Users/roocky/Library/Python/2.7/bin/ghp-import", line 9, in <module>
    load_entry_point('ghp-import==0.5.4', 'console_scripts', 'ghp-import')()
  File "/Users/roocky/Library/Python/2.7/lib/python/site-packages/ghp_import.py", line 241, in main
    git.check_call('push', opts.remote, opts.branch)
  File "/Users/roocky/Library/Python/2.7/lib/python/site-packages/ghp_import.py", line 106, in check_call
    sp.check_call(['git'] + list(args), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'gh-pages']' returned non-zero exit status 1

Fatal error: local() encountered an error (return code 1) while executing 'ghp-import -p -m "Update output documentation" -r origin -b gh-pages output'

Aborting.
```
错误日志指出远程仓库中的内容比本地内容新，所以要先执行git pull然后再push，然而此时远程仓库中的内容是我初次搭建wiki时的内容，本地的内容实际上要比远程仓库中的内容新。不过我还是试着pull了一下，然后再去执行fab deploy，但是上面错误依然存在。
希望可以在百忙之中抽出时间帮我看一下，非常感谢！
&nbsp;
环境：
- OS：macOS 10.12
- $SHELL：zsh
- Python：2.7.10
- ghp-import：0.5.4
- repository：https://github.com/xroocky/rwiki

**Comment by tankywoo** [comment]
你好，谢谢你对这个项目的支持。

看提示的信息，这个是和git相关的。针对提示，我猜测应该是你本地 gh-pages 分支的 commits和github上的不一致。

目前你的github上，gh-pages有一个提交，commit id 是 `e7e318e`，你可以本地`git checkout gh-pages`切换到这个分支，通过 `git log --oneline` 确认是否第一个是这个提交？如果没有则会导致push时冲突。

**Comment by xroocky** [comment]
@tankywoo 感谢回复！
&nbsp;
我在本地通过`git log --oneline`查看了一下gh-pages分支的commit，结果如下:
``` bash
e7e318e wiki init commit
(END)
```
可以看到和GitHub上gh-pages分支的commit是一致的，因此我猜测会不会是我最初在GitHub部署simiki时就有问题了呢？或者是我使用的方式有问题呢？
&nbsp;
在部署simiki之后本地的情况是这样的：
我的wiki所有源文件在`/Wiki`目录，`/Wiki`目录下有一个仓库（该仓库用来管理源文件，忽略`/Wiki/output`目录），该仓库只有一个master分支，对应到GitHub上rwiki仓库中的master分支。
`/Wiki/output`目录下有一个仓库（该仓库用来管理wiki的HTML和CSS文件），该仓库只有一个gh-pages分支，对应到GitHub上rwiki仓库中的gh-pages分支。
总结来说就是本地有两个仓库，每个仓库各有一个分支，本地这两个仓库的分支对应到GitHub上一个仓库的两个分支。
&nbsp;
我的使用方式：
修改完`/Wiki/content`目录下的源文件后，在`/Wiki`目录下执行`fab commit`&`git push -u origin master`命令先将源文件push到GitHub上的master分支中，然后在`/Wiki`目录下执行`simiki g`&`fab deploy`命令来将`/Wiki/output`目录下的内容push到GitHub上的gh-pages分支中。
&nbsp;
虽然在`/Wiki`目录下执行`fab deploy`命令会有push冲突，但是我在`/Wiki/output`目录下手动执行`git push origin gh-pages`命令却不会有冲突，可以顺利更新GitHub上gh-pages分支的内容，所以我猜测会不会是`fab deploy`命令在我的环境下执行出现了问题呢？
&nbsp;
因为我不是太懂Python，所以以下只是我的个人猜测：
针对GitHub Pages部署方式，deploy命令似乎是执行了`ghp-import -p -m "Update output documentation" -r origin -b gh-pages output`命令，在ghp-import的源码中可以在main()方法中找到以下代码：
``` python
run_import(git, args[0], opts)

if opts.push:
    if opts.force:
        git.check_call('push', opts.remote, opts.branch, '--force')
    else:
        git.check_call('push', opts.remote, opts.branch)
```
我阅读了一下run_import和git.check_call方法的源码，在这里就不贴出来了，run_import方法应该是在执行commit操作，其中`args[0]`就是`ghp-import -p -m "Update output documentation" -r origin -b gh-pages output`命令中最后的output。下面的`git.check_call('push', opts.remote, opts.branch)`方法应该是在执行push操作，但是我不明白为什么这里不需要传入`args[0]`呢？如果没有output作为参数，此处执行的push命令不就是相当于在`/Wiki`目录下执行`git push origin gh-pages`了吗？再看看之前`fab deploy`命令报错日志中最后一行就是`subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'gh-pages']' returned non-zero exit status 1`，然而在`/Wiki`目录下根本没有gh-pages分支，所以肯定会有push冲突。
&nbsp;
希望Tanky Woo不吝赐教！

**Comment by tankywoo** [comment]
@xroocky 

> 我的wiki所有源文件在/Wiki目录，/Wiki目录下有一个仓库（该仓库用来管理源文件，忽略/Wiki/output目录），该仓库只有一个master分支，对应到GitHub上rwiki仓库中的master分支。
/Wiki/output目录下有一个仓库（该仓库用来管理wiki的HTML和CSS文件），该仓库只有一个gh-pages分支，对应到GitHub上rwiki仓库中的gh-pages分支。
> 总结来说就是本地有两个仓库，每个仓库各有一个分支，本地这两个仓库的分支对应到GitHub上一个仓库的两个分支。

如果如你上面所描述的，那这块确实有点问题。

原因也如你说的一样：

> 再看看之前fab deploy命令报错日志中最后一行就是subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'gh-pages']' returned non-zero exit status 1，然而在/Wiki目录下根本没有gh-pages分支，所以肯定会有push冲突。

---

简单描述下部署以及ghp-import的原理吧。

假设目录结构:

    -- /home/wiki/
    ---- .git/
    ---- .gitignore
    ---- content/
    ---- themes/
    ---- ...
    ---- output/


因为用了`ghp-import`这个工具，所以不需要在我文档中提到的手动配置的部署过程。只需要本地(/home/wiki/)下，编辑content中的wiki文件，然后提交master，其中`.gitignore`中排除了`output/*`目录，所以在master下，generate对output的变更是不会有diff了。

编辑完后，**当前目录下**执行`fab deploy`，按配置的话，实际命令也就是`ghp-import -p -m "Update output documentation" -r origin -b gh-pages output`。即遍历output目录，针对每个文件，和之前的gh-pages分支提交历史作对比，如果有差异则提交 (具体细节比较复杂，代码是直接写的原生数据)。

这里有两点可以确认的地方：

1. 在master分支下, cd output/ 并不会改变分支，而根据你的描述，cd 到output下后, 你执行`git branch`应该会看到 `gh-pages`
2. 在`/home/wiki`下，执行 `git checkout gh-pages`切换到gh-pages分支，那么任然在/home/wiki目录下，但是文件都变为gh-pages分支下的内容了。两个分支的目录在存放上来看是平级的。

而你的配置方案，看起来像Simiki文档中之前写的原生手动配置部署的方案？

**Comment by xroocky** [comment]
@tankywoo 
问题已经解决啦，真的非常非常感谢：）如你所料，我之前就是采用的原生手动配置部署方案，至于为什么……可能因为当时我觉得手动部署的步骤比较详细吧(ಥ_ಥ)
&nbsp;
PS：提个小小的建议，如果文档中`fab deploy`自动部署的部分可以再详细一点的话，那么对我这种理解能力不太好的用户可能体验会更加友好一些，当然这只是我个人的一个小看法了😂，最后向你再次感谢！祝元宵节快乐！

**Comment by tankywoo** [comment]
你好，解决就好。😊

谢谢你的建议，这几天我会把文档再补充下，包括手动部署这块的说明和fab deploy的基本原理。

有其他使用上的问题和建议的话欢迎再提issue👍

万象 <notifications@github.com>于2017年2月11日周六 17:20写道：

**Comment by xroocky** [comment]
不客气😂，好的！期待补充后的文档：）
