### ISSUE TITLE
Windows10下不能使用中文文件名和目录名？

### ISSUE THREAD

**Issue by himao** [tankywoo/simiki#88]
Windows10下使用中文文件名和目录名，simiki g生成静态文件正常（output包含中文目录和文件），simiki p访问本机预览，首页显示正常，点击中文条目，报404，浏览器地址栏URL正常，包含正确的中文路径。是Windows下中文编码问题吗？

**Comment by tankywoo** [comment]
你好，应该是编码问题导致，可能和 Python 的 http server handler 处理有关，这周我部署一个 win 测试环境调式下。👍

你也可以提供更多的信息：

- Python 版本
- `simiki p` 显示的访问日志

**Comment by himao** [comment]
Python版本：2.7.13
`simiki p`日志：
D:\Wiki>simiki p
127.0.0.1 - - [22/Mar/2017 21:46:25] code 404, message File not found
127.0.0.1 - - [22/Mar/2017 21:46:25] "GET /%E4%B8%AD%E6%96%87%E7%9B%AE%E5%BD%95/test.html HTTP/1.1" 404 -  
中间那一串路径在浏览器中显示是`/中文目录/`四个汉字。

**Comment by tankywoo** [comment]
@himao 感谢你提供的信息，昨晚已经初步定位是文件系统编码问题，之前只考虑前后端统一都是 `utf-8` 的情况。

这个问题我会抓紧修复的。
