### ISSUE TITLE
源码包在linux下如何生成output

### ISSUE THREAD

**Issue by FlyHan** [tankywoo/simiki#92]
另外在个人网站如何更新simiki

**Comment by tankywoo** [comment]
建议通过 pip 安装

更新 simiki 具体是指更新 simiki 的版本还是更新什么？

**Comment by FlyHan** [comment]
更新是指内容更新如何提交到网站上更新

今天新增文件遇到好像中文不支持

**Comment by tankywoo** [comment]
更新站点参考 [Simiki - 部署](http://simiki.org/zh-docs/deploy.html)

中文文件名报错，请具体贴下相关的信息：

* 目录名/文件名
* 操作系统
* Python 版本
* Simiki 版本

谢谢

**Comment by FlyHan** [comment]
/home/fly/share/test/wiki/content/tools/常用工具.md
Ubuntu 14.04.5 LTS
Python 2.7.6
Simiki 1.6.0.1

**Comment by tankywoo** [comment]
比较奇怪，我这边测试都ok。

麻烦再帮忙提供一些信息：

1. `_config.yml` 中加一行：`debug: True` 开启 debug 再生成看看详细的错误信息
2. 执行 `locale` 的结果

**Comment by FlyHan** [comment]
[DEBUG]: Empty the destination directory
Traceback (most recent call last):
  File "/usr/local/bin/simiki", line 9, in <module>
    load_entry_point('simiki==1.6.0.1', 'console_scripts', 'simiki')()
  File "/usr/local/lib/python2.7/dist-packages/simiki/cli.py", line 401, in main
    generator.generate(include_draft=args['--draft'])
  File "/usr/local/lib/python2.7/dist-packages/simiki/cli.py", line 178, in generate
    self.generate_tags()
  File "/usr/local/lib/python2.7/dist-packages/simiki/cli.py", line 206, in generate_tags
    files = [f for f in files if not f.startswith(".")]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)

/share/test/wiki$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by tankywoo** [comment]
因为代码里是作了编码转换（`unicode_literals`），想不出来哪里会导致这块问题。

目前能想到的就是 `self.config['source']` 变量是 str 而不是 unicode。

进一步确认只能改代码了，如果可以的话，需要修改文件 `/usr/local/lib/python2.7/dist-packages/simiki/cli.py`，在 205 行上下添加以下代码：

```
from pprint import pprint  # 添加1
pprint(self.config)  # 添加2
for root, dirs, files in os.walk(self.config["source"]):  # 原来的 205 行
    [print(type(f)) for f in files]  # 添加3
    files = [f for f in files if not f.startswith(".")]  # 原来的 206 行
    ...
```

**Comment by Xuanwo** [comment]
我在 py 2.7 上试了一下，`os.walk()` 的 top 参数 str 和 unicode 都是接受的，不会出现编解码的问题才对：

```python
>>> os.walk(u"测试")
<generator object walk at 0x7f24183a1d20>
>>> os.walk("测试")
<generator object walk at 0x7f24183a1b90>
```

除非是这样

```python
>>> os.walk(u"测试".encode())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

f.startswith(".") 这边我也试了一下，os.walk 返回的元祖都是 str，不知道是否相关。

**Comment by Xuanwo** [comment]
https://github.com/tankywoo/simiki/blob/master/simiki/cli.py#L380 这个函数执行的结果不符合预期，args没有被正确decode。我猜想 @FlyHan  是不是直接通过命令行参数指定的文件名？

**Comment by tankywoo** [comment]
@Xuanwo 是的，如果 `os.walk` 的路径是 str 的话，files 是 str；如果是 unicode，返回的就是 unicode。根据报错信息，目前也只能是这块的问题。

但是我在 config 里作了 `unicode_literals` 的处理，所以想不明白哪块没生效。

**Comment by Xuanwo** [comment]
@FlyHan 可以贴一下你的配置文件以及使用 simiki 的命令么？

**Comment by FlyHan** [comment]
前几天没上。。。
_config.yml内容：
# Document:
# http://simiki.org/docs/configuration.html

url: http://wiki.flyhan.com
title: FlyHan的Wiki
keywords: wiki Linux
description: 
author: FlyHan

root: /
source: content
destination: output
themes_dir: themes
theme: simple2

category:
  - name: linux  # 目录名
    label: Linux  # 目录的别名, 生成首页时可以使用
  - name: tools
    label: tools

default_ext: md
pygments: true
debug: true

使用命令 simiki g

**Comment by tankywoo** [comment]
@Xuanwo 

FlyHan 的报错是：

> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)

这个是出现在 str 和 unicode 混用，`"."` 是 unicode，但是 `f` 是 str，Python 会尝试做默认的 `decode()` 但是默认编码 ascii 无法解码。

@FlyHan 

看看我的这条回复：<https://github.com/tankywoo/simiki/issues/92#issuecomment-297960292>，看看能否协助？

**Comment by FlyHan** [comment]
@tankyoo
我试一下，初步分析原因是在windows创建的文件，在Ubuntu编译出的错误，已经用notepad++转换过为UNIX格式

**Comment by FlyHan** [comment]
@tankywoo 
添加代码之后的打印
```
test/wiki$ simiki g
[DEBUG]: Empty the destination directory
{u'attach': u'attach',
 u'author': 'FlyHan',
 'category': [{'label': 'Linux', 'name': 'linux'},
              {'label': 'tools', 'name': 'tools'}],
 u'debug': True,
 u'default_ext': 'md',
 u'description': u'',
 u'destination': 'output',
 u'keywords': 'wiki Linux',
 u'pygments': True,
 u'root': '/',
 u'source': 'content',
 u'theme': 'simple2',
 u'themes_dir': 'themes',
 u'time': datetime.datetime(2017, 5, 2, 19, 43, 54, 480865, tzinfo=<DstTzInfo 'Asia/Shanghai' CST+8:00:00 STD>),
 u'title': u'FlyHan\u7684Wiki',
 u'url': 'http://wiki.flyhan.com',
 u'version': '1.6.0.1'}
<type 'str'>
<type 'str'>
<type 'str'>
<type 'str'>
Traceback (most recent call last):
  File "/usr/local/bin/simiki", line 9, in <module>
    load_entry_point('simiki==1.6.0.1', 'console_scripts', 'simiki')()
  File "/usr/local/lib/python2.7/dist-packages/simiki/cli.py", line 403, in main
    generator.generate(include_draft=args['--draft'])
  File "/usr/local/lib/python2.7/dist-packages/simiki/cli.py", line 178, in generate
    self.generate_tags()
  File "/usr/local/lib/python2.7/dist-packages/simiki/cli.py", line 208, in generate_tags
    files = [f for f in files if not f.startswith(".")]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
```

**Comment by tankywoo** [comment]
@FlyHan 非常感谢 👍 

我已经知道原因了，以前在 yaml 这块踩过坑，它导入的是 str。然后配置 os.walk 会对编码做一致性处理，所以就出问题了。

目前你可以将配置文件 `_config.yml` 中的下面两行删掉临时解决，因为这些就是默认配置，不需要手动去写。稍后我将修复这块问题。

```
source: content
destination: output
```

CC @Xuanwo

**Comment by FlyHan** [comment]
@tankywoo 
配置删除两行后问题还存在的
```
test/wiki$ simiki g
{u'attach': u'attach',
 u'author': 'FlyHan',
 'category': [{'label': 'Linux', 'name': 'linux'},
              {'label': 'tools', 'name': 'tools'}],
 u'debug': False,
 u'default_ext': 'md',
 u'description': u'',
 u'destination': u'output',
 u'keywords': 'wiki Linux',
 u'pygments': True,
 u'root': '/',
 u'source': u'content',
 u'theme': 'simple2',
 u'themes_dir': 'themes',
 u'time': datetime.datetime(2017, 5, 3, 12, 10, 34, 374663, tzinfo=<DstTzInfo 'Asia/Shanghai' CST+8:00:00 STD>),
 u'title': u'FlyHan\u7684Wiki',
 u'url': 'http://wiki.flyhan.com',
 u'version': '1.6.0.1'}
<type 'unicode'>
<type 'unicode'>
<type 'unicode'>
Traceback (most recent call last):
  File "/usr/local/bin/simiki", line 9, in <module>
    load_entry_point('simiki==1.6.0.1', 'console_scripts', 'simiki')()
  File "/usr/local/lib/python2.7/dist-packages/simiki/cli.py", line 404, in main
    generator.generate(include_draft=args['--draft'])
  File "/usr/local/lib/python2.7/dist-packages/simiki/cli.py", line 178, in generate
    self.generate_tags()
  File "/usr/local/lib/python2.7/dist-packages/simiki/cli.py", line 217, in generate_tags
    meta, _ = g.get_meta_and_content(do_render=False)
  File "/usr/local/lib/python2.7/dist-packages/simiki/generators.py", line 134, in get_meta_and_content
    meta_str, content_str = self.extract_page(self._src_file)
  File "/usr/local/lib/python2.7/dist-packages/simiki/generators.py", line 197, in extract_page
    match_obj = re.match(regex, fd.read())
  File "/usr/lib/python2.7/codecs.py", line 296, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb3 in position 12: invalid start byte
```

**Comment by tankywoo** [comment]
这个是文件字符集编码的问题，可以通过 `file /home/fly/share/test/wiki/content/tools/常用工具.md` 来确认（如果是这个文件的话）

解决方法是通过命令或工具转换为 utf-8，以 [`iconv`](https://en.wikipedia.org/wiki/Iconv) 为例：

```
# -f 的编码以 file 命令的结果为准
iconv -f gbk -t utf-8 -o /path/to/output_file /path/to/input_file
```

**Comment by FlyHan** [comment]
已OK[握手]

**Comment by tankywoo** [comment]
@FlyHan 非常感谢，发现了这个问题。如果还有其它问题欢迎继续提 Issue。 👍
