### ISSUE TITLE
推送多个远程库

### ISSUE THREAD

**Issue by yi-Xu-0100** [tankywoo/simiki#96]
系统：`ubuntu16.04`
配置：`github`项目页（打算同时配置在`coding`上）
问题：不太清楚`_config.yml`中该怎么写`deploy`，希望能够同时推送两个远程库。
致谢：感谢`simiki`的作者，能够带来这样简约的作品。

**Comment by tankywoo** [comment]
你好，部署可以参考：<http://simiki.org/zh-docs/deploy.html#github-pages>

如果你想推送到 github 和 coding 两个地方，可以使用两个 remote 地址（具体可以看看 git remote）。

**Comment by yi-Xu-0100** [comment]
因为想两边都提供静态网页部署，但分支名字不同，我试着用bash写了个脚本处理一下了。

hexo的好像有支持，但是是在deploy里加的内容，先暂时这样，也在学习python，如果有可能，希望以后能够对这个有添加。

谢谢作者了。
